### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by crossSulation** [bnoordhuis/node-heapdump#100]
C:\Users\Administrator\Documents\pomelo_workspace\chatofpomelo-websocket\game-server\node_modules\heapdump\build\addon.
vcxproj(20,3): error MSB4019: can't find project path “C:\Microsoft.Cpp.Default.props”。please make sure <Import> Path is correct

**Comment by bnoordhuis** [comment]
Please post the full output.

**Comment by crossSulation** [comment]
In the common/node/swagger.js , you most export params by prototype , for example 
At the Swagger constructor
you need asign
this.params =params;
Swagger.protoryp.params=function() {
return this.params;
}
or else, you can't get params outside the module

**Comment by bnoordhuis** [comment]
That seems strangely off-topic, not to mention late.  I'll close this.
