### ISSUE TITLE
Error: unexpected end of file at Zlib._handle.onerror (zlib.js:370:17)

### ISSUE THREAD

**Issue by jlory** [bnoordhuis/node-heapdump#104]
I'm trying to install the module in an existing project, I got that error:

( Using Node 6.10.3 + Ubuntu 16.04 )

> jlory@jlory-ubuntu:~/git/bos-friends$ npm install heapdump --save
> 
> heapdump@0.3.9 install /home/jlory/git/bos-friends/node_modules/heapdump
> node-gyp rebuild
> 
> gyp WARN install got an error, rolling back install
> gyp ERR! configure error 
> gyp ERR! stack Error: unexpected end of file
> gyp ERR! stack     at Zlib._handle.onerror (zlib.js:370:17)
> gyp ERR! System Linux 4.4.0-78-generic
> gyp ERR! command "/opt/nodejs/node-v6.10.3-linux-x64/bin/node" "/opt/nodejs/node-v6.10.3-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /home/jlory/git/bos-friends/node_modules/heapdump
> gyp ERR! node -v v6.10.3
> gyp ERR! node-gyp -v v3.4.0
> gyp ERR! not ok 
> npm ERR! Linux 4.4.0-78-generic
> npm ERR! argv "/opt/nodejs/node-v6.10.3-linux-x64/bin/node" "/usr/bin/npm" "install" "heapdump" "--save"
> npm ERR! node v6.10.3
> npm ERR! npm  v3.10.10
> npm ERR! code ELIFECYCLE
> 
> npm ERR! heapdump@0.3.9 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the heapdump@0.3.9 install script 'node-gyp rebuild'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the heapdump package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp rebuild
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs heapdump
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls heapdump
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/jlory/git/bos-friends/npm-debug.log

**Comment by bnoordhuis** [comment]
Just try again, that's normally a transient error.  It means the tarball that npm downloaded from the registry was corrupt.  Clean out your local npm cache as well.

**Comment by jlory** [comment]
I think the problem is corporate MITM SSL certs, it looks like your package needs https://nodejs.org/download/release/v6.10.3/node-v6.10.3-headers.tar.gz so our network might inject some data along the way...

> gyp verb extracted file from tarball include/node/openssl/asn1t.h
> gyp WARN install got an error, rolling back install
> gyp verb command remove [ '6.10.3' ]
> gyp verb remove using node-gyp dir: /home/jlory/.node-gyp
> gyp verb remove removing target version: 6.10.3
> gyp verb remove removing development files for version: 6.10.3
> gyp verb extracted file from tarball include/node/openssl/bio.h
> gyp verb extracted file from tarball include/node/openssl/blowfish.h
> gyp ERR! configure error 
> gyp ERR! stack Error: read ECONNRESET
> gyp ERR! stack     at exports._errnoException (util.js:1018:11)
> gyp ERR! stack     at TLSWrap.onread (net.js:568:26)
> gyp ERR! System Linux 4.4.0-78-generic
> gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /home/jlory/git/bos-friends/node_modules/heapdump
> gyp ERR! node -v v6.10.3
> gyp ERR! node-gyp -v v3.4.0
> gyp ERR! not ok 

I have either that TLS error or the previous Zlib one. Still investigating ...

**Comment by jlory** [comment]
Closing it since it's not related to the package ;)
