### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by lynka** [bnoordhuis/node-heapdump#105]
Hi.  I'm new in nodejs and heapdump.  Would you please help me?  The following shows when I install heapdump.  Thank you very much in advance. 

[root@localhost ~] #.node --version
v4.1.1
[root@localhost node_modules] #.npm install heapdump
|
> heapdump@0.3.9 install /usr/local/xxx/service/node_modules/heapdump
> node-gyp rebuild

make: Entering directory `/usr/local/xxx/service/node_modules/heapdump/build'
  CXX(target) Release/obj.target/addon/src/heapdump.o
In file included from /root/.node-gyp/4.1.1/include/node/node.h:42,
                 from ../src/heapdump.cc:15:
/root/.node-gyp/4.1.1/include/node/v8.h:336: error: expected unqualified-id before ‘using’
/root/.node-gyp/4.1.1/include/node/v8.h: In constructor ‘v8::MaybeLocal<T>::MaybeLocal()’:
/root/.node-gyp/4.1.1/include/node/v8.h:353: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/4.1.1/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::IsEmpty() const’:
/root/.node-gyp/4.1.1/include/node/v8.h:360: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/4.1.1/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::ToLocal(v8::Local<S>*) const’:
/root/.node-gyp/4.1.1/include/node/v8.h:364: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/4.1.1/include/node/v8.h: In member function ‘bool v8::WeakCallbackInfo<T>::IsFirstPass() const’:
/root/.node-gyp/4.1.1/include/node/v8.h:430: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/4.1.1/include/node/v8.h: At global scope:
/root/.node-gyp/4.1.1/include/node/v8.h:469: error: expected unqualified-id before ‘using’
/root/.node-gyp/4.1.1/include/node/v8.h: In constructor ‘v8::Global<T>::Global()’:
/root/.node-gyp/4.1.1/include/node/v8.h:790: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/4.1.1/include/node/v8.h: In constructor ‘v8::Global<T>::Global(v8::Global<T>&&)’:
/root/.node-gyp/4.1.1/include/node/v8.h:815: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/4.1.1/include/node/v8.h: In member function ‘v8::Global<T>& v8::Global<T>::operator=(v8::Global<S>&&)’:
/root/.node-gyp/4.1.1/include/node/v8.h:827: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/4.1.1/include/node/v8.h: At global scope:
/root/.node-gyp/4.1.1/include/node/v8.h:852: error: expected unqualified-id before ‘using’
/root/.node-gyp/4.1.1/include/node/v8.h:1089: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/4.1.1/include/node/v8.h:1095: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/4.1.1/include/node/v8.h: In member function ‘v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const’:
/root/.node-gyp/4.1.1/include/node/v8.h:3205: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/4.1.1/include/node/v8.h: In member function ‘v8::Local<T> v8::MaybeLocal<T>::ToLocalChecked()’:
/root/.node-gyp/4.1.1/include/node/v8.h:7151: error: ‘nullptr’ was not declared in this scope
../src/heapdump.cc: At global scope:
../src/heapdump.cc:52: error: ‘v8::Handle’ has not been declared
make: *** [Release/obj.target/addon/src/heapdump.o] Error 1
make: Leaving directory `/usr/local/xxx/service/node_modules/heapdump/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/nodejs/node_bin/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 2.6.32-573.7.1.el6.x86_64
gyp ERR! command "/usr/local/nodejs/node_bin/bin/node" "/usr/local/nodejs/node_bin/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/xxx/service/node_modules/heapdump
gyp ERR! node -v v4.1.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Linux 2.6.32-573.7.1.el6.x86_64
npm ERR! argv "/usr/local/nodejs/node_bin/bin/node" "/usr/local/bin/npm" "install" "heapdump"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE

npm ERR! heapdump@0.3.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the heapdump@0.3.9 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the heapdump package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls heapdump
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/xxx/service/node_modules/npm-debug.log

**Comment by bnoordhuis** [comment]
You need a C++11-capable compiler, g++ >= 4.8.5 or clang++ >= 3.4.
