### ISSUE TITLE
error when install heapdump

### ISSUE THREAD

**Issue by freeozyl80** [bnoordhuis/node-heapdump#107]
i got erro just like 
![rtx](https://user-images.githubusercontent.com/8967606/27582412-5dcf3744-5b63-11e7-8dd4-c7625f31a0cb.png)
i have python 2.7 and vs 2012, i think it was enough for this installing, but the error i got above,

**Comment by bnoordhuis** [comment]
You need VS 2013 or newer.  That's not a requirement of heapdump itself, by the way - building add-ons for node 4 or up doesn't work with VS 2012.

**Comment by freeozyl80** [comment]
I have installed vs 2015 and uninstall 2012, then i got error like original error:
![rtx](https://user-images.githubusercontent.com/8967606/27618447-21205abc-5bef-11e7-9daf-553823bb8023.png)
it means can't load VCBuild.exe, but i have alreay has vs 2015, what should i do? thanks for your help

**Comment by bnoordhuis** [comment]
Pass `--msvs_version=2015` to npm.  If that doesn't work, google that MSB3428 error code and you'll find several links with solutions.
