### ISSUE TITLE
Parallel installation fails

### ISSUE THREAD

**Issue by runk** [bnoordhuis/node-heapdump#111]
I know it's not ideal and not meant to be done this way, but this is how some CI platforms work. When you have one disk drive and run several pipelines in parallel, each of them does `npm i`. Only one of them succeed, other fails with:

> pyenv: cannot rehash: /var/lib/jenkins/.pyenv/shims/.pyenv-shim exists

Issue described in https://github.com/pyenv/pyenv/issues/174. Not sure if anything can be done in this project, just FYI.

**Comment by bnoordhuis** [comment]
Thanks for the report but that's not under node-heapdump's control.  I'll close this out.
