### ISSUE TITLE
Chrome dev tools taking forever to load heapsnapshot

### ISSUE THREAD

**Issue by chaithuzz2** [bnoordhuis/node-heapdump#113]
First of all, thanks for this amazing module. I have a problem in loading one of my heap snapshots.

I have a heapdump file which is around 65 MB and it took 60-90 minutes to load in to the chrom dev tools.

To compare I have another heapdump file which is around 230 MB and it's been 3 hrs since chrome dev tools got stuck at Building dominator tree.

<img width="857" alt="screen shot 2017-11-09 at 5 57 59 pm" src="https://user-images.githubusercontent.com/3799830/32605479-969c59f2-c577-11e7-81b4-b779bbcb9e40.png">

Does it usually take this much time to load ? How can I make it faster ?

Are there any dev tools other than Chrome dev tools where I can compare the two snapshots ? 

I tried node-inspector and it's not even able to load.

**Comment by bnoordhuis** [comment]
That sounds like a Devtools bug, probably a variation on https://github.com/bnoordhuis/node-heapdump/issues/50#issuecomment-106581153 (summary: deep cycles.)  Not much you can do except report to Chrome/Devtools.

> Are there any dev tools other than Chrome dev tools where I can compare the two snapshots ?

No.  I have a bunch of scripts I use for prying data from snapshots that I might publish someday, but I don't have time right now to turn them into something that is usable for anyone that isn't me.

That said, a .heapsnapshot is just a big JSON object.  You can already get some useful data out of it from the node REPL.

**Comment by dvejmz** [comment]
Can confirm this is happening to me too. I'm trying to load in a 181MB heapsnapshot and it's stuck at the "Building dominator tree" stage.

**Comment by dvejmz** [comment]
Reported this problem on the Chromium bugtracker and it looks like a "WontFix" unfortunately.

Bug report here: https://bugs.chromium.org/p/chromium/issues/detail?id=901007

**Comment by bnoordhuis** [comment]
Thank you for doing that. If it's an algorithmic limitation, then I'm afraid there isn't really anything that can be done about it. I'll add a warning to the readme.

**Comment by gannons** [comment]
@bnoordhuis is there any means of taking a snapshot and saving it to disk without building the dominator tree?

**Comment by bnoordhuis** [comment]
@gannons The dominator tree is built by Devtools, not heapdump.

**Comment by gannons** [comment]
@bnoordhuis thanks for clarifying
