### ISSUE TITLE
Is it possible to install using latest node version(eg. 8.x.x) ?

### ISSUE THREAD

**Issue by jdm85kor** [bnoordhuis/node-heapdump#114]
<img width="266" alt="2018-02-05 5 00 32" src="https://user-images.githubusercontent.com/7186594/35795892-14bd4b50-0a9e-11e8-9afc-199c26a26ae6.png">

<img width="958" alt="2018-02-05 6 01 43" src="https://user-images.githubusercontent.com/7186594/35796106-ba3edc06-0a9e-11e8-8905-850f8c7ea2b8.png">

I'm trying to install.
I did node-gyp configure build.

But I couldn't see 'build/Debug' directory.

I must use node ver 8.x.x in order to dependency..
Is there a way to intall heapdump using node 8.x.x?

**Comment by bnoordhuis** [comment]
v8.x is supported.  How did you install heapdump?

**Comment by jdm85kor** [comment]
hi! @bnoordhuis 
I did like below.

npm install heapdump --save
(move to node_modules/heapdump) node-gyp configure build
and then type this codes.

<img width="528" alt="2018-02-05 6 15 58" src="https://user-images.githubusercontent.com/7186594/35796691-b63661a4-0aa0-11e8-8180-f06a69db892f.png">

thanks your reply.

**Comment by bnoordhuis** [comment]
> (move to node_modules/heapdump) node-gyp configure build

You shouldn't need to build it manually.  Can you delete node_modules/heapdump and install it again, and post everything that npm prints?

**Comment by jdm85kor** [comment]
I did delete heapdump. and install again like below.

<img width="1011" alt="2018-02-05 6 56 10" src="https://user-images.githubusercontent.com/7186594/35798504-57e13394-0aa6-11e8-82d3-3b27526a4347.png">


<img width="628" alt="2018-02-05 6 59 46" src="https://user-images.githubusercontent.com/7186594/35798658-cf1bace6-0aa6-11e8-8ac2-11fd19d90559.png">

**Comment by bnoordhuis** [comment]
I suspect you're building it for either the wrong node version or the wrong architecture, e.g. ia32 instead of x64.  What does `node-gyp -v rebuild` print?

**Comment by jdm85kor** [comment]
@bnoordhuis , I did node-gyp -v rebuild 

<img width="1371" alt="2018-02-05 11 34 15" src="https://user-images.githubusercontent.com/7186594/35810078-df474900-0acd-11e8-8245-ed8f46a90448.png">
<img width="1370" alt="2018-02-05 11 34 45" src="https://user-images.githubusercontent.com/7186594/35810085-e611e43e-0acd-11e8-931c-5b63e3fd778e.png">
<img width="1379" alt="2018-02-05 11 34 55" src="https://user-images.githubusercontent.com/7186594/35810100-ebf5929c-0acd-11e8-8c05-d3236ac4698e.png">

**Comment by bnoordhuis** [comment]
Well, that looks alright.  You mentioned you were using 8.9.3 but the screenshots say 8.9.4.  Do you have multiple node binaries installed?  What do `node -p process.versions` and `node -p process.arch` print?

**Comment by jdm85kor** [comment]
@bnoordhuis so sorry. It's my mistake.
8.9.4 is right.
thanks for your help :)

<img width="250" alt="2018-02-06 3 22 15" src="https://user-images.githubusercontent.com/7186594/35844587-a2b3023e-0b51-11e8-8865-684de7f930a5.png">

<img width="105" alt="2018-02-06 3 22 27" src="https://user-images.githubusercontent.com/7186594/35844610-b5778fd4-0b51-11e8-90cc-84f2944688ae.png">

**Comment by bnoordhuis** [comment]
That looks correct.  What happens when you run this?
```
node -p 'require("./node_modules/heapdump/build/Release/addon.node")`
```

**Comment by jdm85kor** [comment]
@bnoordhuis I did it.

<img width="688" alt="2018-02-06 4 36 56" src="https://user-images.githubusercontent.com/7186594/35846973-11b35c06-0b5c-11e8-9394-f80d2e453f3d.png">

**Comment by bnoordhuis** [comment]
Okay, if that works, then I'm afraid I don't know what the issue is.

**Comment by jdm85kor** [comment]
<img width="673" alt="2018-02-06 6 15 49" src="https://user-images.githubusercontent.com/7186594/35850955-db26b2a6-0b69-11e8-95e6-9a3451c8878f.png">

**Comment by bnoordhuis** [comment]
heapdump's index.js first tries to load the Release add-on and falls back to trying the Debug add-on (because that's uncommon, it's built when you pass `--debug`.).  It's not unexpected that the Debug add-on isn't there.

**Comment by jdm85kor** [comment]
thanks @bnoordhuis  
I'll try again.
