### ISSUE TITLE
Module not found: Error: Can't resolve '../build/Debug/addon'

### ISSUE THREAD

**Issue by Karthikmuthupandi** [bnoordhuis/node-heapdump#116]
When I try to build my application with heapdump node modules, I am getting the below error,
```
ERROR in ./~/heapdump/lib/main.js
    Module not found: Error: Can't resolve '../build/Debug/addon' in '/node_modules/heapdump/lib'
     @ ./~/heapdump/lib/main.js 21:14-45
```
I am using Node version: v6.11.0
Npm version: 3.10.10

Could you please to resolve this issue?

**Comment by bnoordhuis** [comment]
That stack trace looks very unusual... how did you install iconv and what did it print in the build step?

**Comment by bnoordhuis** [comment]
You're running node-gyp from the wrong directory, you should cd into node_modules/heapdump first.

I'm closing this out as OP never followed up.  @a-barbieri Can you open a new issue if it's still not working for you?
