### ISSUE TITLE
Saved heapdumps are empty

### ISSUE THREAD

**Issue by Ishidres** [bnoordhuis/node-heapdump#117]
In my node application I try to save heapdumps like this:
```js
const heapdump = require('heapdump');
heapdump.writeSnapshot('./heapsnapshots/' + Date.now() + '.heapsnapshot', function(err, filename) {
  console.log('Dump written to ', filename);
});
```

Some heap snaphots have content, but for some reason some heap snapshots are completely empty (0 bytes size).
Also, there are no error logs in console. It just saves an empty heap snapshot.

My node version is **v8.11.1** and node-heapdump is on **v0.3.9**.
Why are those heap snapshots empty?

**Comment by bnoordhuis** [comment]
Have you seen https://github.com/bnoordhuis/node-heapdump#caveats in the docs?

**Comment by Ishidres** [comment]
I'm sorry, I have missed it.
I guess that solves the issue.

Thanks for your help! :smiley:
