### ISSUE TITLE
fork heap dump documentation

### ISSUE THREAD

**Issue by polomsky** [bnoordhuis/node-heapdump#119]
Please document if fork heapdump can be used with newer nodejs (e.g. 8.x, 10.x).
I would like to use it on production.
I made few test on my dev machine (with node 8.9.4) at I see nothing wrong with results on first sight.

Motivation:
- I have memory leak on production and I need to make lag-less heap dump of production server
- during my testing I found that heap dump of my test machine (123MB) caused lag of 5 seconds so I am afraid that 4GB of prod's memory could cause long downtime

**Comment by bnoordhuis** [comment]
> Please document if fork heapdump can be used with newer nodejs (e.g. 8.x, 10.x).

It's right there in the documentation but if you want the abridged version: no, it's unreliable and prone to crash.
