### ISSUE TITLE
failing installing

### ISSUE THREAD

**Issue by fragender** [bnoordhuis/node-heapdump#128]
I tried to install heapdump according to the instructions and got the following errors (I do not have Python on my system):

C:\Users\Ich\node_modules\heapdump>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:154:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Ich\node_modules\heapdump
gyp ERR! node -v v10.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Ich\package.json'
npm WARN Ich No description
npm WARN Ich No repository field.
npm WARN Ich No README data
npm WARN Ich No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! heapdump@0.3.13 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the heapdump@0.3.13 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ich\AppData\Roaming\npm-cache\_logs\2019-04-27T14_14_21_039Z-debug.log

**Comment by bnoordhuis** [comment]
See [here](https://github.com/nodejs/node-gyp#option-1), that should download everything you need to build native add-ons.

**Comment by fragender** [comment]
thank you! I will try

**Comment by fragender** [comment]
I write node/javascript. Do I need Python, then?

**Comment by bnoordhuis** [comment]
You do if you want to use native add-ons. Those are written in C++ and use a build tool that's written in Python.
