### ISSUE TITLE
how long does it take to take a snapshot?

### ISSUE THREAD

**Issue by calibr** [bnoordhuis/node-heapdump#130]
Sorry for asking this kind of question here, but the stackoverflow tag seems to be not very active. 
I have a nodejs process which had consumed 2.8G of memory on the time when I decided to take a snapshot of the process to investigate memory leaks. I ran snapshotting with `kill -USR2 <PID>`. After 30 minutes the process is consuming ~11G of memory and there is file `heapdump-4994352412.969650.heapsnapshot` in the process working dir, but it is empty. Should I wait more or something went wrong and the snapshot won't be created?

 I have checked dmesg and it seems it doesn't contain any problem info(OOM, limits, etc.)

**Comment by bnoordhuis** [comment]
A snapshot, even of a big heap, usually doesn't take more than a few seconds. You're probably hitting some V8 issue but if there's an easy way for me to reproduce, I can look into it. I've fixed snapshotting bugs in V8 before.

**Comment by calibr** [comment]
Got it, thanks for the info. It is a production server and the node process had been working for two months until it reached 2.8G memory consumption, so I don't think it will be easy to reproduce.

After I ran the snapshotting the process stopped processing requests(it is a web server), cpu usage was very low 0-1%, memory consumption grew up to 11GB and then was changing within 11 and 12 GB.
`strace` for the process during the snapshotting:
```
[pid 11455] brk(0x23d928000 [wait(0x857f) = 11455] WIFSTOPPED,sig=133
)            = 0x23d928000
 [wait(0x857f) = 11455] WIFSTOPPED,sig=133
[pid 11455] brk(0x23d949000 [wait(0x857f) = 11455] WIFSTOPPED,sig=133
)            = 0x23d949000
 [wait(0x857f) = 11455] WIFSTOPPED,sig=133
[pid 11455] brk(0x23d96a000 [wait(0x857f) = 11455] WIFSTOPPED,sig=133
)            = 0x23d96a000
 [wait(0x857f) = 11455] WIFSTOPPED,sig=133
[pid 11455] brk(0x23d98b000 [wait(0x857f) = 11455] WIFSTOPPED,sig=133
)            = 0x23d98b000
 [wait(0x857f) = 11455] WIFSTOPPED,sig=133
[pid 11455] brk(0x23d9ac000 [wait(0x857f) = 11455] WIFSTOPPED,sig=133
)            = 0x23d9ac000
 [wait(0x857f) = 11455] WIFSTOPPED,sig=133
[pid 11455] brk(0x23d9cd000 [wait(0x857f) = 11455] WIFSTOPPED,sig=133
)            = 0x23d9cd000
 [wait(0x857f) = 11455] WIFSTOPPED,sig=133
[pid 11455] brk(0x23d9ee000 [wait(0x857f) = 11455] WIFSTOPPED,sig=133
)            = 0x23d9ee000
... the same messages...
```

Probably we can close the issue for now, because I already killed this process and have no more info

**Comment by bnoordhuis** [comment]
Okay, thanks for the update. I'll close this out but let me know if there's more I can do.

Those brk() calls are node/V8 allocating memory in 132k chunks. It probably means it was still working on building the snapshot.
