### ISSUE TITLE
Possible memory leak in node-heapdump?

### ISSUE THREAD

**Issue by jk1z** [bnoordhuis/node-heapdump#134]
Node version: 10.16.0
node-heapdump version: 0.3.14
Expected behaviour: Memory goes down after the heap dump because of the node gc.
Actual behaviour: Memory stays the same whole time after the heap dump.

Is that expected behaviour? I made the heapdump module into a hapi route. Here is the snippet below. Thanks in advance for taking the effort of looking into this issue.
```
handler: async (request, h) => {
                try {
                    const result = await (promisify(Heapdump.writeSnapshot))('/heapdumps/' + Moment.tz(Env.TZ_DEFAULT).format("YYYY-MM-DD_HHmmss") + '.heapsnapshot');
                    return h.response(result);
                } catch (err) {
                    throw Errors.boom(err, request);
                }
            }
```

![image](https://user-images.githubusercontent.com/18542127/62938642-c37dc880-be12-11e9-9507-d6ae679db303.png)

**Comment by bnoordhuis** [comment]
Non-heap is RSS / the C/C++ heap? That's not completely unexpected, it's possible the libc memory manager cannot return the memory to the operating system because of memory fragmentation (or because it simply decides not to due to some heuristic.)

If you're on Linux, you can check with strace that brk system calls or mmap/munmap calls roughly pair up. See https://github.com/nodejs/node/issues/8871#issuecomment-250915913 for an example.

**Comment by jk1z** [comment]
> Non-heap is RSS / the C/C++ heap? That's not completely unexpected, it's possible the libc memory manager cannot return the memory to the operating system because of memory fragmentation (or because it simply decides not to due to some heuristic.)
> 
> If you're on Linux, you can check with strace that brk system calls or mmap/munmap calls roughly pair up. See [nodejs/node#8871 (comment)](https://github.com/nodejs/node/issues/8871#issuecomment-250915913) for an example.

Unfornatually I can't run `strace -cfe mmap,munmap,mprotect,brk -p pid` in the docker container I'm getting `strace: attach: ptrace(PTRACE_ATTACH, 73): Operation not permitted` error. Is there any other way I can test if it's a **memory fragmentation** not **a memory leak**?
