### ISSUE TITLE
fails install with node 8, mac

### ISSUE THREAD

**Issue by Bodasia** [bnoordhuis/node-heapdump#136]
```
> heapdump@0.3.15 install /.../node_modules/heapdump
> node-gyp rebuild

  CXX(target) Release/obj.target/addon/src/heapdump.o
../src/heapdump.cc:104:26: error: use of undeclared identifier 'errno'
  if (fp == NULL) return errno;
                         ^
../src/heapdump.cc:109:25: error: use of undeclared identifier 'errno'
  if (fclose(fp)) err = errno;
                        ^
2 errors generated.
make: *** [Release/obj.target/addon/src/heapdump.o] Error 1
```

**Comment by bnoordhuis** [comment]
There's something wrong with your compiler or your system although I can't exactly say what. `errno` is a variable that comes from the system header `<errno.h>`, that heapdump.cc includes.

**Comment by Bodasia** [comment]
I'm trying on clear system with fresh xcode, and have same result

**Comment by Bodasia** [comment]
the problem only with 0.3.15.
0.3.14 - work perfectly

**Comment by Bodasia** [comment]
also, I install last ruby and try install package again, this sing not help.

**Comment by bnoordhuis** [comment]
v0.3.15 is the release that introduced the use of `errno` but again, this is an issue with your system's build toolchain (the compiler and the system headers), not node-heapdump.

> I install last ruby

Ruby? Do you mean node?
