### ISSUE TITLE
node-gyp command options

### ISSUE THREAD

**Issue by Dhq** [bnoordhuis/node-heapdump#137]
Hi! 

node-gyp tries to fetch node headers from nodejs.org. On our build server that is not possible, so we would like to set the `--proxy` option to the node-gyp command. I can't figure out how to do that. Is it possible?

**Comment by bnoordhuis** [comment]
Did you mean to post this over at nodejs/node-gyp? Your question is only related to node-iconv insofar that it uses node-gyp as its build tool - but then so do most native modules.

**Comment by Dhq** [comment]
@bnoordhuis Yes, after some more debugging on my own I can see that this question might have been a bit misdirected. :) Thanks anyway.
