### ISSUE TITLE
Heapdump with nodemon

### ISSUE THREAD

**Issue by PrakharPatidar** [bnoordhuis/node-heapdump#141]
I am collecting heapdump only when calling upon by an API endpoint by exposing a router get method and that's working well. But when using nodemon during development somehow nodemon not able to restart the server and heapdump collecting the snapshot and placing in root project directory. So after few saving nodemon is triggering and heapdump generating the files at root. 

Am i doing something worng?

**Comment by bnoordhuis** [comment]
nodemon and node-heapdump both use SIGUSR2. Check the README for the `nosignal` option.
