### ISSUE TITLE
Error: The specified procedure could not be found.

### ISSUE THREAD

**Issue by p-g-krish** [bnoordhuis/node-heapdump#142]
> C:\users\dev\tmp\leak>node run.js
> C:\users\dev\node_modules\heapdump\index.js:18
>   if (e.code !== 'MODULE_NOT_FOUND') throw e;
>                                      ^
> 
> Error: The specified procedure could not be found.
> \\?\C:\users\dev\node_modules\heapdump\build\Release\addon.node
>     at Object.Module._extensions..node (internal/modules/cjs/loader.js:807:18)
>     at Module.load (internal/modules/cjs/loader.js:653:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
>     at Module.require (internal/modules/cjs/loader.js:692:17)
>     at require (internal/modules/cjs/helpers.js:25:18)
>     at Object.<anonymous> (C:\users\dev\\node_modules\heapdump\index.js:16:15)
>     at Module._compile (internal/modules/cjs/loader.js:778:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
>     at Module.load (internal/modules/cjs/loader.js:653:32)

after installing this module, when i run the script facing this above error

**Comment by bnoordhuis** [comment]
Node.js and node-heapdump version?

**Comment by p-g-krish** [comment]
Node version - **v10.16.3**
Heapdump version - **0.3.15**

**Comment by bnoordhuis** [comment]
Can you delete `node_modules` and run `npm install` again? Please post the output.

**Comment by p-g-krish** [comment]
It's working after delete the node_modules and reinstalled the module.

Thanks
