### ISSUE TITLE
Heapdump with workers

### ISSUE THREAD

**Issue by BorisKozo** [bnoordhuis/node-heapdump#143]
Hi,

I am trying to use this package with workers on node 12.6.2. 
If you try to require it from several workers there is an error.
If I require it from the main execution "thread" only and do a dump while there is a worker doing something in the background, what do I get?

Thanks.

**Comment by bnoordhuis** [comment]
There's no support for worker threads yet. Adding that support is somewhat complicated by the fact that the most common way of taking a snapshot is by sending a signal, and signalling a specific thread is... challenging... on some platforms.

(And that's assuming there's a 1-to-1 correspondence between worker threads and systems threads. There is today but that might not be true tomorrow.)

**Comment by BorisKozo** [comment]
Thank you for the explanation.
From your response I understand that no matter from which thread I will call it I will get the memory of the main thread, right?

**Comment by bnoordhuis** [comment]
Currently yes.

If I made the changes to support worker threads, and you signal the process as a whole rather than an individual thread, then an arbitrary thread would get snapshotted. Which thread receives the signal is non-deterministic.
