### ISSUE TITLE
which node process will this dump when there are more than 1 node web processes?

### ISSUE THREAD

**Issue by jiajianrong** [bnoordhuis/node-heapdump#145]
It should be common more than 1 node web app run on a virtual machine.
And it should be common we use PM2 to create more process for each node web app.

So my question is how do we know which node app/process the dump file stands for?

**Comment by bnoordhuis** [comment]
Are you asking for the PID to be included in the filename? If you use the `heapdump.writeSnapshot()` function, you can do it like this:
```js
heapdump.writeSnapshot(`${process.pid}-${Date.now()}.heapsnapshot`)
```
I'd be open to change the default filename to include the PID as well but I worry a little it might break downstream users. There are (somewhat to my amazement) over 1500 packages that depend on node-heapdump so I can't check them by hand.
