### ISSUE TITLE
Unexpected loop of heapsnapshots

### ISSUE THREAD

**Issue by alexbjorlig** [bnoordhuis/node-heapdump#148]
I'm trying to implement at /GET endpoint on my express server, that will generate a `heapsnapshot`, and send it to the client. The code looks like this:

```typescript
app.get('/heapdump, (req, res) => {
  const heapdumpOnDiscName = await getHeatMap();
  res.attachment(heapdumpOnDiscName);
  const readStream = createReadStream(heapdumpOnDiscName);
  readStream.pipe(res);

  res.on('finish', () => console.log('finished'));
  readStream.on('end', () => unlinkSync(heapdumpOnDiscName));
});

async function getHeatMap(): Promise<string> {
    console.log(`getHeatMap is running`);
    return new Promise((resolve, reject) => {
        writeSnapshot(function (err, filename) {
            if (err) {
                console.error(`Failed with '${err?.message}'`);
                return reject(err);
            } else {
                console.error(`Wrote heampdump to  '${filename}'`);
                return resolve(filename);
            }
        });
    });
}
```

However when I run this I get some _very_ unexpected results. In the console I get the output I expect, and I actually get the file as requested when the heapsnapshot is done. But then after some time, for example triggered by a restart of the node process, new heapsnapshots are generated, without any output to the console 🤔  ?

Is there something wrong with how I wrap the `writeSnapshot` or do I misunderstand something completely here?

**Comment by bnoordhuis** [comment]
> after some time, for example triggered by a restart of the node process, new heapsnapshots are generated, without any output to the console

I'm not sure how I should read that: you restart the node process, make a request (with your browser? curl?) and receive a response but nothing is logged to the console? Try changing `app.get` to `app.post`.

**Comment by alexbjorlig** [comment]
Thanks for taking time to answer, and a great repo. Our project is build with webpack, and when any files are changed nodemon restarts the process. To process to replicate this issue is to:

1. Start the server first time, no issues.
2. Hit the `/heapdump` endpoint with postman/insomnia, and the heapdump is downloaded as expected - it works🥳 
3. Change _any_ file, and webpack rebuilds the project. Now nodemon attempts to restart the process, but nothing happens and heapdumps are generated continuously?

I guess it's one of those issues that can be really hard without a reproducible example - I will try to find the time to create one.

**Comment by bnoordhuis** [comment]
Ah, the presence of `nodemon` is a crucial piece of information here - see #21.

node-heapdump installs a SIGUSR2 handler but that's also the signal that nodemon uses to restart processes. The clash is unfortunate but there's a paucity of signals that are free for use.

The `NODE_HEAPDUMP_OPTIONS=nosignal` environment variable disables node-heapdump's signal handler. You can either set that on the command line or in `process.env` if you do it before you load node-heapdump.

**Comment by alexbjorlig** [comment]
Amazing - I will try to fix it with the `NODE_HEAPDUMP_OPTIONS ` variable.

Would it be possible to add that as an option somehow, without setting an env variable? Because if the env variable is the only option, I have to inform everyone else on the team and make sure they have the env variable enabled?

If you think it could make sense, I would be happy to assist with the implementation if it could be any help?

**Comment by bnoordhuis** [comment]
Glad to hear it's working for you now!

As to adding a programmatic option: it's not an unreasonable feature request. But.

As I mentioned in the other issue, I kind of like that node-heapdump's API is so dead simple and I'd rather keep it that way.
