### ISSUE TITLE
heap snapshot triggers exit code 137 despite plenty of available memory

### ISSUE THREAD

**Issue by tsheaff** [bnoordhuis/node-heapdump#149]
## Issue

When triggering a heapdump, either through the `-USR2` signal, or through code with `heapdump.writeSnapshot()`, the process fails with exit code 137. This leaves the heapdump at 0 bytes

Using `htop` during the snapshotting, the heapdump takes 1 of the 8 cores up to 100% CPU, and it uses at most 2.5GB / 15GB of the available memory. Then it suddenly dies (usually after around 40 - 60s).

When investigating with `dmesg`, there are no logs from this incidents there.

When snapshotting locally for the same application in a fresh state, it's about a 75MB heap file size. Per the 2x memory rule of thumb in the README, would expect the memory used to be well under the 15GB available. And `htop` (and `ps` as well) both confirm that the memory usage is not above the available threshold (tho CPU is rather high)

## Setup

* Node app running in docker with in a `node:12-buster-slim` container
* Hosted inside Kubernetes on AWS. Doesn't occur in local docker on OSX with the same container, tho not sure if this is relevant
* 15GB available memory and 8 cores of CPU.
* `ulimit -v` and `ulimit u` both return `unlimited`

@bnoordhuis thoughts on how to debug this further?

**Comment by tsheaff** [comment]
I'm able to repro something similar using a node REPL like this:

```
Welcome to Node.js v12.18.4.
Type ".help" for more information.
> const heapdump = require('heapdump');
undefined
> const moment = require('moment');
undefined
> const leaky = [];
undefined
> for (let i = 0; i < 20000000; i += 1) {
... leaky.push(`my leaky string has value ${i}`);
... }
20000000
> const filename = `${moment().format()}-from-api.heapsnapshot`;
undefined
> filename;
'2020-10-08T00:04:37+00:00-from-api.heapsnapshot'
> heapdump.writeSnapshot(filename);
Killed
```

This does not fail when the loop index is set to 10M instead of 20M. In that case it just produces a large heapsnapshot file filled with 10M of those strings, as expected. So there's some limit that this heap snapshot has., which makes sense. The issue in the case described above is that the snapshot should not be nearly big enough to be failing in this way.

**Comment by bnoordhuis** [comment]
Exit code 137 means the process was terminated with SIGKILL (and it's indeed saying "Killed") so my best guess is that you indeed have a run-in with the kernel's OOM killer.

Try `strace -o trace.log -f node app.js` - the last lines in the log file should tell you who sent the signal.

**Comment by tsheaff** [comment]
Hey thanks for the super fast and great reply @bnoordhuis 

For posterity: We ended up resolving this. It was actually our Kubernetes liveness probe, because the node process was busy creating the heapdump, it wasn't able to respond, and after 60s Kubernetes was restarting the pod. Once we stopped the liveness probe in our testing the heapdump completed.

Not an issue with heapdump itself. Closing.
