### ISSUE TITLE
Can't resolve '../build/Debug/addon' 

### ISSUE THREAD

**Issue by mwasigala** [bnoordhuis/node-heapdump#150]
i installed the heapdump and configured the build but when i run the application i get the below error

This relative module was not found:

* ./build/Debug/addon in ./node_modules/heapdump/index.js

**Comment by bnoordhuis** [comment]
That probably means it failed to build - it's a module with a native component. What does `npm install heapdump` print?

**Comment by mwasigala** [comment]
<img width="770" alt="heapdump" src="https://user-images.githubusercontent.com/20720317/97779777-7e69c180-1b91-11eb-8f69-67fe650d632e.PNG">

**Comment by bnoordhuis** [comment]
Looks healthy. Can you `require('heapdump')` after that? If not, can you post the output of `node -p process.versions`?

**Comment by mwasigala** [comment]
<img width="169" alt="Process versions" src="https://user-images.githubusercontent.com/20720317/97789186-6dd83c00-1bcf-11eb-9601-be4cfb4ff4ae.PNG">

**Comment by bnoordhuis** [comment]
I'd recommend upgrading to the latest v14.x release, v14.13.1. I can't guarantee it works with older releases, there's been a lot of changes since v14.4.0:
```
$ git diff --shortstat  v14.4.0..v14.13.1
 4175 files changed, 303431 insertions(+), 121938 deletions(-)
```
That said, I have a sneaking suspicion what's causing the error. What does `node -p process.arch` print?

**Comment by mwasigala** [comment]
x64

**Comment by bnoordhuis** [comment]
Then I'm afraid I'm out of suggestions. My hunch was that heapdump was compiled for x64 but your build of node wasn't.

**Comment by mwasigala** [comment]
I did update node but the result is still the same

**Comment by ParshantMehra** [comment]
I am running into same issue..

**Comment by sifrenette** [comment]
If you are using webpack consider adding heapdump to your externals if it's not already done, it fixed the problem for me

**Comment by mwasigala** [comment]
@sifrenette Unfortunately your solution won't work for me

What is the file ./build/Release/addon  for ?because when I visit the Release folder there is no addon file which has no extension...

**Comment by marcelkottmann** [comment]
Hi there, I had the same error running the application in a test setup (with jest). The ./build/Release/addon or ./build/Debug/addon  error message is midleading, because the actual file is addon.node
I debugged the actual error by adding a `throw e` directly in the ./node_modules/heapdump/index.js  by changing
the code block
```
try {
  var addon = require('./build/Release/addon');
} catch (e) {
  if (e.code !== 'MODULE_NOT_FOUND') throw e;
  var addon = require('./build/Debug/addon');
}

```
to
```
try {
  var addon = require('./build/Release/addon');
} catch (e) {
  if (e.code !== 'MODULE_NOT_FOUND') throw e;
  throw e;
  var addon = require('./build/Debug/addon');
}

```
When you run your application next time, you see the original error. In my case the jest configuration had to be updated to also allow the file extenision *.node
The error may occur also in other setup where requiring addon, does not resolve to addon.node

**Comment by peter-afs** [comment]
> In my case the jest configuration had to be updated to also allow the file extenision *.node

This was what worked for me too:

```
-  moduleFileExtensions: ['ts', 'js', 'html'],
+  moduleFileExtensions: ['ts', 'js', 'html', 'node'],
```
