### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by mwasigala** [bnoordhuis/node-heapdump#151]
I followed all the instructions for installing heapdump but I get a build error a missing build for addon please help....

**Comment by bnoordhuis** [comment]
If this is the same issue as the one you reported in #150 then please don't file duplicates. If it's a different issue, then please provide more details.

**Comment by mwasigala** [comment]
It is the same
I duplicated because I was left hanging...

I tried two different computers but still I get the same results when I open the heapdump file there is no build folder but the index.js file source code tries to access that addon which is supposed to be on the build folder....

**Comment by bnoordhuis** [comment]
Let's move it back to the other issue. Apropos this:

> there is no build folder

The screenshot you posted shows it ending up in `build/Release/addon.node`, which is the expected place.
