### ISSUE TITLE
Heapdumps can generate from code but won't respond to the -USR2 signal

### ISSUE THREAD

**Issue by muldoon2007** [bnoordhuis/node-heapdump#153]
Hi,

I'd really like to be able to use this library to get a snapshot of a running application on demand.

I've been able to generate a heapdump using the sample code:

```
import { logger } from './logger';
import heapdump = require('heapdump');

startApp();
heapdump.writeSnapshot((err, filename) => {
  logger.info('dump written to', filename);
});
```

However I'm unable to get the application to respond to the -USR2 signal, both on native Mac (Catalina, 10.15.7), or inside a Docker container running Debian (also on my Mac). Below is an example from inside the Docker shell. You can see there IS a snapshot in the directory already. That one was generated with the code above. But then when I try the `kill` commands I don't see any additional snapshots generated. You can see I poke around in some other directories to look for the snapshot but I didn't find it.

```
# pwd
/home/node/app
# ls
heapdump-199118608.653171.heapsnapshot	node_modules  package-lock.json  package.json  src  tsconfig.json
# ps -aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  1.6  1.9 673072 38744 ?        Ssl  17:52   0:00 npm
root        19  0.0  0.0   4284   804 ?        S    17:52   0:00 sh -c ts-node src/app.ts | bunyan
root        20  117 40.0 1314180 815888 ?      Rl   17:52   0:32 node /home/node/app/node_modules/.bin/ts-node src/app.ts
root        21  0.2  1.4 566084 29460 ?        Sl   17:52   0:00 node /home/node/app/node_modules/.bin/bunyan
root        34  0.1  0.0   4280   752 pts/0    Ss   17:52   0:00 /bin/sh
root        41  0.0  0.1  36636  2644 pts/0    R+   17:52   0:00 ps -aux
# kill -USR2 21
# kill -USR2 20
# ls
heapdump-199118608.653171.heapsnapshot	node_modules  package-lock.json  package.json  src  tsconfig.json
# cd ..
# ls
app
# cd ..
# ls
node
# cd ..
# ls
bin  boot  dev	etc  home  lib	lib64  media  mnt  opt	proc  root  run  sbin  srv  sys  tmp  usr  var
# cd /home/node/app
# kill -USR2 34

[Process completed]


```

One other thing to note: when I try to kill the Bunyan (logging) PID with the command `kill -USR2 21`, I do see this logged out by the application: `User defined signal 2`.

I saw pretty similar results when on my native Mac. Any debugging tips or pointers would be very helpful. Maybe there's something else I need to set up in the JS code that I haven't done yet.

**Comment by bnoordhuis** [comment]
Does it work when you run `node app.js` directly (no bunyan or ts-node) and then signal the process?

**Comment by muldoon2007** [comment]
This is a Typescript service, so I think I have to use `ts-node`, otherwise I get syntax errors when I try `node src/app.ts`. 

I did remove bunyan and retry, but that didn't help.

**Comment by bnoordhuis** [comment]
You can transpile TS to JS, right? My hunch is that ts-node might be interfering with the signal handling, testing with plain node should validate that.

**Comment by muldoon2007** [comment]
I see, let me try out transpiling the TS to JS. I'm afraid to admit I haven't done that before.

**Comment by muldoon2007** [comment]
You're right. After I transpiled to JS and ran that code with `node src/app.js` (running on MacOS), I was able to generate the heap dump with the `kill -USR2` command.

**Comment by bnoordhuis** [comment]
Happy to hear that was helpful.

I'll go ahead and close this out then. Perhaps the ts-node people can shed some light on what's interfering here. Maybe some reload mechanism?
