### ISSUE TITLE
kill -USR2 <pid> creates 2 snapshots

### ISSUE THREAD

**Issue by amit777** [bnoordhuis/node-heapdump#154]
Hi, I was trying out the module and wanted to see if it's expected behavior for 2 snapshots to get created if I run kill -USR2 <pid>?

If it's relevant, I was trying it on a process managed by the cluster module.  Node 14.16.0 on centos8.

**Comment by bnoordhuis** [comment]
Two ways that can happen. You:

1. Send the signal to the process group rather than an individual process (i.e., it gets delivered to both master and worker)

2. Install the signal listener twice (only applies if you call `process.on("SIGSUR2", ...)` yourself)

**Comment by amit777** [comment]
Awesome, thank you! I think it was due to #1.
