### ISSUE TITLE
RSS memory is not 'returned' after heap dump completes

### ISSUE THREAD

**Issue by npomfret** [bnoordhuis/node-heapdump#160]
I am using heap dump to investigate the cause of a memory leak in my application.  I am charting the RSS used (as well as heap used and external memory).  When I invoke the heap dump the RSS used shoots up (as expected) but it does not come down again after the heap dump is finished.  

Is this pattern expected?  Or is there something I need to invoke to recover that memory?

<img width="1726" alt="Screenshot 2021-06-04 at 11 11 10" src="https://user-images.githubusercontent.com/5489469/120785950-9473a200-c525-11eb-89b2-7c211232ee94.png">

**Comment by bnoordhuis** [comment]
That's expected on at least two levels. Some state is retained to make snapshot diffing possible, and even when that memory is released, it may not be returned to the operating system because of fragmentation.
