### ISSUE TITLE
AWS Lambda support?

### ISSUE THREAD

**Issue by rprovodenko** [bnoordhuis/node-heapdump#164]
Hey guys. Thanks for this module!

Question: is this library expected to be working in the AWS Lambda runtime? I keep getting segfaults (sometimes dumping succeeds, sometimes it doesn't). I'm debugging a memory leak that takes place over the whole lifetime of a warm lambda (i.e. across multiple invocations) but this segfault causes the runtime to exit and be recreated prohibiting me from getting to the state where the heap would contain some useful info. The fact that you can't force GC in AWS Lambda also doesn't help.

Interestingly, I'm getting the exact same segfault when using https://www.npmjs.com/package/@airbnb/node-memwatch 

Makes me think there is something in AWS Lambda runtime that makes it incompatible with these libraries.  Do you have any info on this?

The error looks like this:
```
RequestId: f82f9c54-82ad-57ba-ad4f-c62e807123d7 Error: Runtime exited with error: signal: segmentation fault (core dumped)
Runtime.ExitError
```

**Comment by bnoordhuis** [comment]
> Hey guys. Thanks for this module!

Just guy, singular, but you're welcome. :-)

To your question: I've never tried it so... maybe?

I expect Lambda has strict memory limits in place and that can prevent heap snapshots from working. Rule of thumb is a snapshot (temporarily) doubles the memory footprint.

**Comment by rprovodenko** [comment]
Yeah, I read that in the docs, however I was testing in a 10 GB setup with memory usage always below 1 GB. So that shouldn't be the reason. Oh well, maybe I'll get around to looking more closely into it at some point. Thanks!
