### ISSUE TITLE
Is it possible to define a default location for writing heap dumps to?

### ISSUE THREAD

**Issue by kriston13** [bnoordhuis/node-heapdump#168]
This would be very useful in kubernetes environments, where I want to write it to a mounted PVC so that I can persist the heap dumps pass the container/pod dying.
Especially for the heap snapshots that are being taken with the `USR2` signal.

I imagine being able to set it as a configurable env var would be the easiest way for usage?

**Comment by bnoordhuis** [comment]
It's not supported directly but you can cobble it together like this:
```js
process.on("SIGUSR2", () => {
  heapdump.writeSnapshot(`/path/to/${Date.now()}.heapsnapshot`);
});
```

**Comment by kriston13** [comment]
oooo that's clever. I'll give that a try thank you!

**Comment by kriston13** [comment]
That worked really well. Thank you very much! :D 

Would it be worth adding it to the readme?

**Comment by bnoordhuis** [comment]
Good idea, done in 4ae7785.
