### ISSUE TITLE
Node 16.17.0 & node-gyp 9.1.0 - heapdump errors

### ISSUE THREAD

**Issue by Amitcoh1** [bnoordhuis/node-heapdump#170]
Hi,
I've updated my ndoe version and the node-gyp.
Facing the errors below:

PS C:\Development\HQNorth\North> npm rebuild    
npm ERR! code 1
npm ERR! path C:\Development\HQNorth\North\node_modules\heapdump
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c C:\Users\AMIT~1.COH\AppData\Local\Temp\install-d07d9d3d.cmd
npm ERR! Warning: Missing input files:
npm ERR! C:\Development\HQNorth\North\node_modules\heapdump\build\..\src\compat-inl.h
npm ERR! C:\Development\HQNorth\North\node_modules\heapdump\build\..\src\compat.h
npm ERR! Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
npm ERR!   heapdump.cc
npm ERR!      Creating library C:\Development\HQNorth\North\node_modules\heapdump\build\Release\addon.lib and object C:\Development\HQNorth\North\node_modules\heapdump\build\Release\addon.exp
npm ERR! heapdump.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: class v8::HeapSnapshot const * __cdecl v8::HeapProfiler::TakeHeapSnapshot(class v8::ActivityControl *,class v8::HeapProfiler::ObjectNameResolver *)" (__imp_?TakeHeapSnapshot@HeapProfiler@v8@@QEAAPEBVHeapSnapshot@2@PEAVActivityControl@2@PEAVObjectNameResolver@12@@Z) [C:\Development\HQNorth\North\node_modules\heapdump\build\addon.vcxproj]
npm ERR! heapdump.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: static class v8::Local<class v8::FunctionTemplate> __cdecl v8::FunctionTemplate::New(class v8::Isolate *,void (__cdecl*)(class v8::FunctionCallbackInfo<class v8::Value> const &),class v8::Local<class v8::Value>,class v8::Local<class v8::Signature>,int,enum v8::ConstructorBehavior,enum v8::SideEffectType)" (__imp_?New@FunctionTemplate@v8@@SA?AV?$Local@VFunctionTemplate@v8@@@2@PEAVIsolate@2@P6AXAEBV?$FunctionCallbackInfo@VValue@v8@@@2@@ZV?$Local@VValue@v8@@@2@V?$Local@VSignature@v8@@@2@HW4ConstructorBehavior@2@W4SideEffectType@2@@Z) [C:\Development\HQNorth\North\node_modules\heapdump\build\addon.vcxproj]
npm ERR!     Hint on symbols that are defined and could potentially match:
npm ERR!       "__declspec(dllimport) public: static class v8::Local<class v8::External> __cdecl v8::External::New(class v8::Isolate *,void *)" (__imp_?New@External@v8@@SA?AV?$Local@VExternal@v8@@@2@PEAVIsolate@2@PEAX@Z)
npm ERR!       "__declspec(dllimport) public: static class v8::Local<class v8::Integer> __cdecl v8::Integer::New(class v8::Isolate *,int)" (__imp_?New@Integer@v8@@SA?AV?$Local@VInteger@v8@@@2@PEAVIsolate@2@H@Z)
npm ERR!       "__declspec(dllimport) public: static class v8::Local<class v8::ObjectTemplate> __cdecl v8::ObjectTemplate::New(class v8::Isolate *,class v8::Local<class v8::FunctionTemplate>)" (__imp_?New@ObjectTemplate@v8@@SA?AV?$Local@VObjectTemplate@v8@@@2@PEAVIsolate@2@V?$Local@VFunctionTemplate@v8@@@2@@Z)
npm ERR! C:\Development\HQNorth\North\node_modules\heapdump\build\Release\addon.node : fatal error LNK1120: 2 unresolved externals [C:\Development\HQNorth\North\node_modules\heapdump\build\addon.vcxproj]
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.1.0
npm ERR! gyp info using node@16.17.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.10.6 found at "C:\Users\amit.cohen_xmcyber\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe"
npm ERR! gyp info find VS using VS2019 (16.11.32106.194) found at:
npm ERR! gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
npm ERR! gyp info find VS run with --verbose for detailed information
npm ERR! gyp info spawn C:\Users\amit.cohen_xmcyber\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'C:\\Development\\HQNorth\\North\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'msvs',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Development\\HQNorth\\North\\node_modules\\heapdump\\build\\config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Development\\HQNorth\\North\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\amit.cohen_xmcyber\\AppData\\Local\\node-gyp\\Cache\\16.17.0\\include\\node\\common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\amit.cohen_xmcyber\\AppData\\Local\\node-gyp\\Cache\\16.17.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\Development\\HQNorth\\North\\node_modules\\node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\amit.cohen_xmcyber\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\16.17.0\\\\<(target_arch)\\\\node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=C:\\Development\\HQNorth\\North\\node_modules\\heapdump',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'C:\\Development\\HQNorth\\North\\node_modules\\heapdump\\build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'build/binding.sln',
npm ERR! gyp info spawn args   '/clp:Verbosity=minimal',
npm ERR! gyp info spawn args   '/nologo',
npm ERR! gyp info spawn args   '/p:Configuration=Release;Platform=x64'
npm ERR! gyp info spawn args ]
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onExit (C:\Development\HQNorth\North\node_modules\node-gyp\lib\build.js:201:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Windows_NT 10.0.22000
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Development\\HQNorth\\North\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Development\HQNorth\North\node_modules\heapdump
npm ERR! gyp ERR! node -v v16.17.0
npm ERR! gyp ERR! node-gyp -v v9.1.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\amit.cohen_xmcyber\AppData\Local\npm-cache\_logs\2022-08-23T13_34_38_878Z-debug-0.log

Any help please?

**Comment by bnoordhuis** [comment]
Looks like you're trying to install a positively ancient version of node-heapdump. Try the latest release.

**Comment by Amitcoh1** [comment]
@bnoordhuis "heapdump": "^0.3.14" 
the latest is "heapdump": "^0.3.15" 

I think it might relates to the node16 version.
also when tried to update to latest ive recieved this:

PS C:\Development\HQNorth\North> npm install heapdump@0.3.15
npm ERR! code 1
npm ERR! path C:\Development\HQNorth\North\node_modules\heapdump
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c C:\Users\AMIT~1.COH\AppData\Local\Temp\install-512b8271.cmd
npm ERR! Warning: Missing input files:
npm ERR! C:\Development\HQNorth\North\node_modules\heapdump\build\..\src\compat-inl.h
npm ERR! C:\Development\HQNorth\North\node_modules\heapdump\build\..\src\compat.h
npm ERR! Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
npm ERR!   heapdump.cc
npm ERR!      Creating library C:\Development\HQNorth\North\node_modules\heapdump\build\Release\addon.lib and object C:\Development\HQNorth\North\node_modules\heapdump\build\Release\addon.exp
npm ERR! heapdump.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: class v8::HeapSnapshot const * __cdecl v8::HeapProfiler::TakeHeapSnapshot(class v8::ActivityControl *,class v8::HeapProfiler::ObjectNameResolver *)" (__imp_?TakeHeapSnapshot@HeapProfiler@v8@@QEAAPEBVHeapSnapshot@2@PEAVActivityControl@2@PEAVObjectNameResolver@12@@Z) [C:\Development\HQNorth\North\node_modules\heapdump\build\addon.vcxproj]
npm ERR! heapdump.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: static class v8::Local<class v8::FunctionTemplate> __cdecl v8::FunctionTemplate::New(class v8::Isolate *,void (__cdecl*)(class v8::FunctionCallbackInfo<class v8::Value> const &),class v8::Local<class v8::Value>,class v8::Local<class v8::Signature>,int,enum v8::ConstructorBehavior,enum v8::SideEffectType)" (__imp_?New@FunctionTemplate@v8@@SA?AV?$Local@VFunctionTemplate@v8@@@2@PEAVIsolate@2@P6AXAEBV?$FunctionCallbackInfo@VValue@v8@@@2@@ZV?$Local@VValue@v8@@@2@V?$Local@VSignature@v8@@@2@HW4ConstructorBehavior@2@W4SideEffectType@2@@Z) [C:\Development\HQNorth\North\node_modules\heapdump\build\addon.vcxproj]
npm ERR!     Hint on symbols that are defined and could potentially match:
npm ERR!       "__declspec(dllimport) public: static class v8::Local<class v8::External> __cdecl v8::External::New(class v8::Isolate *,void *)" (__imp_?New@External@v8@@SA?AV?$Local@VExternal@v8@@@2@PEAVIsolate@2@PEAX@Z)
npm ERR!       "__declspec(dllimport) public: static class v8::Local<class v8::Integer> __cdecl v8::Integer::New(class v8::Isolate *,int)" (__imp_?New@Integer@v8@@SA?AV?$Local@VInteger@v8@@@2@PEAVIsolate@2@H@Z)
npm ERR!       "__declspec(dllimport) public: static class v8::Local<class v8::ObjectTemplate> __cdecl v8::ObjectTemplate::New(class v8::Isolate *,class v8::Local<class v8::FunctionTemplate>)" (__imp_?New@ObjectTemplate@v8@@SA?AV?$Local@VObjectTemplate@v8@@@2@PEAVIsolate@2@V?$Local@VFunctionTemplate@v8@@@2@@Z)
npm ERR! C:\Development\HQNorth\North\node_modules\heapdump\build\Release\addon.node : fatal error LNK1120: 2 unresolved externals [C:\Development\HQNorth\North\node_modules\heapdump\build\addon.vcxproj]
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.1.0
npm ERR! gyp info using node@16.17.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.10.6 found at "C:\Users\amit.cohen_xmcyber\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe"
npm ERR! gyp info find VS using VS2019 (16.11.32106.194) found at:
npm ERR! gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
npm ERR! gyp info find VS run with --verbose for detailed information
npm ERR! gyp info spawn C:\Users\amit.cohen_xmcyber\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'C:\\Development\\HQNorth\\North\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'msvs',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Development\\HQNorth\\North\\node_modules\\heapdump\\build\\config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Development\\HQNorth\\North\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\amit.cohen_xmcyber\\AppData\\Local\\node-gyp\\Cache\\16.17.0\\include\\node\\common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\amit.cohen_xmcyber\\AppData\\Local\\node-gyp\\Cache\\16.17.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\Development\\HQNorth\\North\\node_modules\\node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\amit.cohen_xmcyber\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\16.17.0\\\\<(target_arch)\\\\node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=C:\\Development\\HQNorth\\North\\node_modules\\heapdump',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'C:\\Development\\HQNorth\\North\\node_modules\\heapdump\\build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'build/binding.sln',
npm ERR! gyp info spawn args   '/clp:Verbosity=minimal',
npm ERR! gyp info spawn args   '/nologo',
npm ERR! gyp info spawn args   '/p:Configuration=Release;Platform=x64'
npm ERR! gyp info spawn args ]
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onExit (C:\Development\HQNorth\North\node_modules\node-gyp\lib\build.js:201:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Windows_NT 10.0.22000
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Development\\HQNorth\\North\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Development\HQNorth\North\node_modules\heapdump
npm ERR! gyp ERR! node -v v16.17.0
npm ERR! gyp ERR! node-gyp -v v9.1.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\amit.cohen_xmcyber\AppData\Local\npm-cache\_logs\2022-08-23T14_48_16_364Z-debug-0.log

**Comment by bnoordhuis** [comment]
I can tell from this:

> npm ERR! C:\Development\HQNorth\North\node_modules\heapdump\build..\src\compat-inl.h
> npm ERR! C:\Development\HQNorth\North\node_modules\heapdump\build..\src\compat.h

That it's 0.3.9 or older (so, at least 5 years old) because those files were removed in 0.3.10. Delete your node_modules folder, maybe your npm cache folder as well, and try again.

**Comment by Amitcoh1** [comment]
Thanks.
Solved!

I just struggled with deleting the cache folder :)
