### ISSUE TITLE
making heapdump snapshot too slow

### ISSUE THREAD

**Issue by yallyyally** [bnoordhuis/node-heapdump#171]
Hello.
First of all, I'm a node js beginner.

I installed the heapdump module to track the heap memory leak in the vm. And I created an api that makes snapshots. 
On the first day of the deployment, a snapshot was successfully taken (approximately 5 seconds), but three days after deployment, the same api was called, but it stopped and did not respond. 

How do I solve this problem? 
I reinstalled the module and tried to redistribute the code, but it didn't work.

**Comment by bnoordhuis** [comment]
Sorry, but this is not a free support forum. You're welcome to report bugs in node-heapdump but you're on your own when it comes to fixing your own code.
