### ISSUE TITLE
 installing heapdump have problems. node@16.15.1,node-gyp@9.3.0,python@3.11.0

### ISSUE THREAD

**Issue by cute1baby** [bnoordhuis/node-heapdump#172]
hello, I encountered the following problems when installing heapdump. Can you help me solve them?

error /Users/lizhong/works/cnhis-design-vue/node_modules/heapdump: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /Users/lizhong/works/cnhis-design-vue/node_modules/heapdump
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@9.1.0
gyp info using node@16.15.1 | darwin | x64
gyp info find Python using Python version 3.11.0 found at "/usr/local/bin/python3"
gyp info spawn /usr/local/bin/python3
gyp info spawn args [
gyp info spawn args   '/Users/lizhong/works/cnhis-design-vue/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/lizhong/works/cnhis-design-vue/node_modules/heapdump/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/lizhong/works/cnhis-design-vue/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/lizhong/Library/Caches/node-gyp/16.15.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/lizhong/Library/Caches/node-gyp/16.15.1',
gyp info spawn args   '-Dnode_gyp_dir=/Users/lizhong/works/cnhis-design-vue/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/lizhong/Library/Caches/node-gyp/16.15.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/lizhong/works/cnhis-design-vue/node_modules/heapdump',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
xcrun: error: missing DEVELOPER_DIR path: /Applications/Xcode.app/Contents/Developer
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (/Users/lizhong/works/cnhis-design-vue/node_modules/node-gyp/lib/build.js:201:23)
gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Darwin 20.5.0
gyp ERR! command "/usr/local/Cellar/nvm/0.37.0/versions/node/v16.15.1/bin/node" "/Users/lizhong/works/cnhis-design-vue/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/lizhong/works/cnhis-design-vue/node_modules/heapdump

**Comment by bnoordhuis** [comment]
The actual build error isn't included. Can you post the full output of `npm install heapdump`?

**Comment by cute1baby** [comment]
It is probably caused by another module. This is a problem for me to install another module.

design-vue git:(release/v3.1.26) ✗ yarn add node-gyp@9.3.0 -W
yarn add v1.22.10
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] 🔍  Resolving packages...
warning imagemin-pngquant > pngquant-bin > bin-build > tempfile > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
[2/4] 🚚  Fetching packages...
info @esbuild/android-arm@0.15.12: The platform "darwin" is incompatible with this module.
info "@esbuild/android-arm@0.15.12" is an optional dependency and failed compatibility check. Excluding it from installation.
info @esbuild/android-arm@0.15.12: The CPU architecture "x64" is incompatible with this module.
info @esbuild/linux-loong64@0.15.12: The platform "darwin" is incompatible with this module.
info "@esbuild/linux-loong64@0.15.12" is an optional dependency and failed compatibility check. Excluding it from installation.
info @esbuild/linux-loong64@0.15.12: The CPU architecture "x64" is incompatible with this module.
info esbuild-freebsd-64@0.15.12: The platform "darwin" is incompatible with this module.
info "esbuild-freebsd-64@0.15.12" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-android-64@0.15.12: The platform "darwin" is incompatible with this module.
info "esbuild-android-64@0.15.12" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-android-arm64@0.15.12: The platform "darwin" is incompatible with this module.
info "esbuild-android-arm64@0.15.12" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-android-arm64@0.15.12: The CPU architecture "x64" is incompatible with this module.
info esbuild-darwin-arm64@0.15.12: The CPU architecture "x64" is incompatible with this module.
info "esbuild-darwin-arm64@0.15.12" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-freebsd-arm64@0.15.12: The platform "darwin" is incompatible with this module.
info "esbuild-freebsd-arm64@0.15.12" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-freebsd-arm64@0.15.12: The CPU architecture "x64" is incompatible with this module.
info esbuild-linux-32@0.15.12: The platform "darwin" is incompatible with this module.
info "esbuild-linux-32@0.15.12" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-linux-32@0.15.12: The CPU architecture "x64" is incompatible with this module.
info esbuild-linux-arm@0.15.12: The platform "darwin" is incompatible with this module.
info "esbuild-linux-arm@0.15.12" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-linux-arm@0.15.12: The CPU architecture "x64" is incompatible with this module.
info esbuild-linux-mips64le@0.15.12: The platform "darwin" is incompatible with this module.
info "esbuild-linux-mips64le@0.15.12" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-linux-mips64le@0.15.12: The CPU architecture "x64" is incompatible with this module.
info esbuild-linux-64@0.15.12: The platform "darwin" is incompatible with this module.
info "esbuild-linux-64@0.15.12" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-linux-s390x@0.15.12: The platform "darwin" is incompatible with this module.
info "esbuild-linux-s390x@0.15.12" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-linux-s390x@0.15.12: The CPU architecture "x64" is incompatible with this module.
info esbuild-linux-riscv64@0.15.12: The platform "darwin" is incompatible with this module.
info "esbuild-linux-riscv64@0.15.12" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-linux-riscv64@0.15.12: The CPU architecture "x64" is incompatible with this module.
info esbuild-linux-arm64@0.15.12: The platform "darwin" is incompatible with this module.
info "esbuild-linux-arm64@0.15.12" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-linux-arm64@0.15.12: The CPU architecture "x64" is incompatible with this module.
info esbuild-linux-ppc64le@0.15.12: The platform "darwin" is incompatible with this module.
info "esbuild-linux-ppc64le@0.15.12" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-linux-ppc64le@0.15.12: The CPU architecture "x64" is incompatible with this module.
info esbuild-netbsd-64@0.15.12: The platform "darwin" is incompatible with this module.
info "esbuild-netbsd-64@0.15.12" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-openbsd-64@0.15.12: The platform "darwin" is incompatible with this module.
info "esbuild-openbsd-64@0.15.12" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-windows-32@0.15.12: The platform "darwin" is incompatible with this module.
info "esbuild-windows-32@0.15.12" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-windows-32@0.15.12: The CPU architecture "x64" is incompatible with this module.
info esbuild-windows-arm64@0.15.12: The platform "darwin" is incompatible with this module.
info "esbuild-windows-arm64@0.15.12" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-windows-arm64@0.15.12: The CPU architecture "x64" is incompatible with this module.
info esbuild-sunos-64@0.15.12: The platform "darwin" is incompatible with this module.
info "esbuild-sunos-64@0.15.12" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-windows-64@0.15.12: The platform "darwin" is incompatible with this module.
info "esbuild-windows-64@0.15.12" is an optional dependency and failed compatibility check. Excluding it from installation.
info @esbuild/linux-loong64@0.14.54: The platform "darwin" is incompatible with this module.
info "@esbuild/linux-loong64@0.14.54" is an optional dependency and failed compatibility check. Excluding it from installation.
info @esbuild/linux-loong64@0.14.54: The CPU architecture "x64" is incompatible with this module.
info esbuild-android-64@0.14.54: The platform "darwin" is incompatible with this module.
info "esbuild-android-64@0.14.54" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-android-arm64@0.14.54: The platform "darwin" is incompatible with this module.
info "esbuild-android-arm64@0.14.54" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-android-arm64@0.14.54: The CPU architecture "x64" is incompatible with this module.
info esbuild-darwin-arm64@0.14.54: The CPU architecture "x64" is incompatible with this module.
info "esbuild-darwin-arm64@0.14.54" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-freebsd-64@0.14.54: The platform "darwin" is incompatible with this module.
info "esbuild-freebsd-64@0.14.54" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-freebsd-arm64@0.14.54: The platform "darwin" is incompatible with this module.
info "esbuild-freebsd-arm64@0.14.54" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-freebsd-arm64@0.14.54: The CPU architecture "x64" is incompatible with this module.
info esbuild-linux-32@0.14.54: The platform "darwin" is incompatible with this module.
info "esbuild-linux-32@0.14.54" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-linux-32@0.14.54: The CPU architecture "x64" is incompatible with this module.
info esbuild-linux-64@0.14.54: The platform "darwin" is incompatible with this module.
info "esbuild-linux-64@0.14.54" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-linux-arm@0.14.54: The platform "darwin" is incompatible with this module.
info "esbuild-linux-arm@0.14.54" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-linux-arm@0.14.54: The CPU architecture "x64" is incompatible with this module.
info esbuild-linux-arm64@0.14.54: The platform "darwin" is incompatible with this module.
info "esbuild-linux-arm64@0.14.54" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-linux-arm64@0.14.54: The CPU architecture "x64" is incompatible with this module.
info esbuild-linux-mips64le@0.14.54: The platform "darwin" is incompatible with this module.
info "esbuild-linux-mips64le@0.14.54" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-linux-mips64le@0.14.54: The CPU architecture "x64" is incompatible with this module.
info esbuild-linux-ppc64le@0.14.54: The platform "darwin" is incompatible with this module.
info "esbuild-linux-ppc64le@0.14.54" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-linux-ppc64le@0.14.54: The CPU architecture "x64" is incompatible with this module.
info esbuild-linux-riscv64@0.14.54: The platform "darwin" is incompatible with this module.
info "esbuild-linux-riscv64@0.14.54" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-linux-riscv64@0.14.54: The CPU architecture "x64" is incompatible with this module.
info esbuild-linux-s390x@0.14.54: The platform "darwin" is incompatible with this module.
info "esbuild-linux-s390x@0.14.54" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-linux-s390x@0.14.54: The CPU architecture "x64" is incompatible with this module.
info esbuild-netbsd-64@0.14.54: The platform "darwin" is incompatible with this module.
info "esbuild-netbsd-64@0.14.54" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-openbsd-64@0.14.54: The platform "darwin" is incompatible with this module.
info "esbuild-openbsd-64@0.14.54" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-sunos-64@0.14.54: The platform "darwin" is incompatible with this module.
info "esbuild-sunos-64@0.14.54" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-windows-32@0.14.54: The platform "darwin" is incompatible with this module.
info "esbuild-windows-32@0.14.54" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-windows-32@0.14.54: The CPU architecture "x64" is incompatible with this module.
info esbuild-windows-64@0.14.54: The platform "darwin" is incompatible with this module.
info "esbuild-windows-64@0.14.54" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-windows-arm64@0.14.54: The platform "darwin" is incompatible with this module.
info "esbuild-windows-arm64@0.14.54" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-windows-arm64@0.14.54: The CPU architecture "x64" is incompatible with this module.
[3/4] 🔗  Linking dependencies...
warning " > vxe-table@4.3.5" has unmet peer dependency "xe-utils@^3.5.0".
warning " > @rollup/plugin-json@4.1.0" has unmet peer dependency "rollup@^1.20.0 || ^2.0.0".
warning "@rollup/plugin-json > @rollup/pluginutils@3.1.0" has unmet peer dependency "rollup@^1.20.0||^2.0.0".
warning " > autoprefixer@10.4.12" has unmet peer dependency "postcss@^8.1.0".
warning " > cssnano@5.1.13" has unmet peer dependency "postcss@^8.2.15".
warning "cssnano > cssnano-preset-default@5.2.12" has unmet peer dependency "postcss@^8.2.15".
warning "cssnano > cssnano-preset-default > css-declaration-sorter@6.3.1" has unmet peer dependency "postcss@^8.0.9".
warning "cssnano > cssnano-preset-default > cssnano-utils@3.1.0" has unmet peer dependency "postcss@^8.2.15".
warning "cssnano > cssnano-preset-default > postcss-calc@8.2.4" has unmet peer dependency "postcss@^8.2.2".
warning "cssnano > cssnano-preset-default > postcss-colormin@5.3.0" has unmet peer dependency "postcss@^8.2.15".
warning "cssnano > cssnano-preset-default > postcss-convert-values@5.1.2" has unmet peer dependency "postcss@^8.2.15".
warning "cssnano > cssnano-preset-default > postcss-discard-comments@5.1.2" has unmet peer dependency "postcss@^8.2.15".
warning "cssnano > cssnano-preset-default > postcss-discard-duplicates@5.1.0" has unmet peer dependency "postcss@^8.2.15".
warning "cssnano > cssnano-preset-default > postcss-discard-empty@5.1.1" has unmet peer dependency "postcss@^8.2.15".
warning "cssnano > cssnano-preset-default > postcss-discard-overridden@5.1.0" has unmet peer dependency "postcss@^8.2.15".
warning "cssnano > cssnano-preset-default > postcss-merge-longhand@5.1.6" has unmet peer dependency "postcss@^8.2.15".
warning "cssnano > cssnano-preset-default > postcss-merge-rules@5.1.2" has unmet peer dependency "postcss@^8.2.15".
warning "cssnano > cssnano-preset-default > postcss-minify-font-values@5.1.0" has unmet peer dependency "postcss@^8.2.15".
warning "cssnano > cssnano-preset-default > postcss-minify-gradients@5.1.1" has unmet peer dependency "postcss@^8.2.15".
warning "cssnano > cssnano-preset-default > postcss-minify-params@5.1.3" has unmet peer dependency "postcss@^8.2.15".
warning "cssnano > cssnano-preset-default > postcss-minify-selectors@5.2.1" has unmet peer dependency "postcss@^8.2.15".
warning "cssnano > cssnano-preset-default > postcss-normalize-charset@5.1.0" has unmet peer dependency "postcss@^8.2.15".
warning "cssnano > cssnano-preset-default > postcss-normalize-display-values@5.1.0" has unmet peer dependency "postcss@^8.2.15".
warning "cssnano > cssnano-preset-default > postcss-normalize-positions@5.1.1" has unmet peer dependency "postcss@^8.2.15".
warning "cssnano > cssnano-preset-default > postcss-normalize-repeat-style@5.1.1" has unmet peer dependency "postcss@^8.2.15".
warning "cssnano > cssnano-preset-default > postcss-normalize-string@5.1.0" has unmet peer dependency "postcss@^8.2.15".
warning "cssnano > cssnano-preset-default > postcss-normalize-timing-functions@5.1.0" has unmet peer dependency "postcss@^8.2.15".
warning "cssnano > cssnano-preset-default > postcss-normalize-unicode@5.1.0" has unmet peer dependency "postcss@^8.2.15".
warning "cssnano > cssnano-preset-default > postcss-normalize-url@5.1.0" has unmet peer dependency "postcss@^8.2.15".
warning "cssnano > cssnano-preset-default > postcss-normalize-whitespace@5.1.1" has unmet peer dependency "postcss@^8.2.15".
warning "cssnano > cssnano-preset-default > postcss-ordered-values@5.1.3" has unmet peer dependency "postcss@^8.2.15".
warning "cssnano > cssnano-preset-default > postcss-reduce-initial@5.1.0" has unmet peer dependency "postcss@^8.2.15".
warning "cssnano > cssnano-preset-default > postcss-reduce-transforms@5.1.0" has unmet peer dependency "postcss@^8.2.15".
warning "cssnano > cssnano-preset-default > postcss-svgo@5.1.0" has unmet peer dependency "postcss@^8.2.15".
warning "cssnano > cssnano-preset-default > postcss-unique-selectors@5.1.1" has unmet peer dependency "postcss@^8.2.15".
warning "cssnano > cssnano-preset-default > postcss-merge-longhand > stylehacks@5.1.0" has unmet peer dependency "postcss@^8.2.15".
warning " > postcss-less@6.0.0" has unmet peer dependency "postcss@^8.3.5".
warning " > rollup-plugin-commonjs@10.1.0" has unmet peer dependency "rollup@>=1.12.0".
warning " > rollup-plugin-terser@7.0.2" has unmet peer dependency "rollup@^2.0.0".
warning " > @cnhis-design-vue/docs@3.1.26-beta.0" has unmet peer dependency "naive-ui@^2.30.0".
warning " > cnhis-design-vue@3.1.26-beta.0" has unmet peer dependency "naive-ui@^2.30.0".
warning " > @cnhis-design-vue/components@3.1.26-beta.0" has unmet peer dependency "naive-ui@^2.30.0".
warning " > @cnhis-design-vue/shared@3.1.26-beta.0" has unmet peer dependency "naive-ui@^2.30.0".
warning "workspace-aggregator-e1938916-957c-4227-8164-89339588963d > @cnhis-design-vue/docs > @vitejs/plugin-vue@2.3.4" has incorrect peer dependency "vite@^2.5.10".
warning "workspace-aggregator-e1938916-957c-4227-8164-89339588963d > cnhis-design-vue > @formily/vue > vue-frag@1.4.1" has incorrect peer dependency "vue@^2.6.0".
[4/4] 🔨  Building fresh packages...
[-/14] ⡀ waiting...
[-/14] ⡀ waiting...
[-/14] ⡀ waiting...
[6/14] ⡀ pngquant-bin
error /Users/lizhong/works/cnhis-design-vue/node_modules/heapdump: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /Users/lizhong/works/cnhis-design-vue/node_modules/heapdump
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@9.3.0
gyp info using node@16.15.1 | darwin | x64
gyp info find Python using Python version 3.11.0 found at "/usr/local/bin/python3"
gyp info spawn /usr/local/bin/python3
gyp info spawn args [
gyp info spawn args   '/Users/lizhong/works/cnhis-design-vue/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/lizhong/works/cnhis-design-vue/node_modules/heapdump/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/lizhong/works/cnhis-design-vue/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/lizhong/Library/Caches/node-gyp/16.15.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/lizhong/Library/Caches/node-gyp/16.15.1',
gyp info spawn args   '-Dnode_gyp_dir=/Users/lizhong/works/cnhis-design-vue/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/lizhong/Library/Caches/node-gyp/16.15.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/lizhong/works/cnhis-design-vue/node_modules/heapdump',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
xcrun: error: missing DEVELOPER_DIR path: /Applications/Xcode.app/Contents/Developer
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (/Users/lizhong/works/cnhis-design-vue/node_modules/node-gyp/lib/build.js:203:23)
gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Darwin 20.5.0
gyp ERR! command "/usr/local/Cellar/nvm/0.37.0/versions/node/v16.15.1/bin/node" "/Users/lizhong/works/cnhis-design-vue/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/lizhong/works/cnhis-design-vue/node_modules/heapdump

**Comment by bnoordhuis** [comment]
Okay, seems it's the same error in both cases:

>  xcrun: error: missing DEVELOPER_DIR path: /Applications/Xcode.app/Contents/Developer

Run `xcode-select` to configure it.
