### ISSUE TITLE
when installing in meteor, it gets wrongly bundled

### ISSUE THREAD

**Issue by atar-axis** [bnoordhuis/node-heapdump#173]
We tried to install the package on a server which is unfortunately still running node 8.16 and meteor 1.8.
Unfortunately we get then the following error:

```
[server-crash] The module ‘/app/bundle/programs/server/npm/node_modules/heapdump/build/Release/addon.node’ was compiled against a different Node.js version using NODE_MODULE_VERSION 83. This version of Node.js requires NODE_MODULE_VERSION 57
```

Does that say something to someone here?
I am digging for hours now without sucess, unfortunately I am not an node or meteor expert and even the meteor guy here gave up.

**Comment by bnoordhuis** [comment]
It's saying the add-on was compiled for a newer node version than what you're running. 83 is Node v14.x, 57 is v8.x ([list](https://nodejs.org/en/download/releases/))

Basically, build with the same version as what you're running in production and you should be good. That said, v8.x is positively ancient and no longer supported by heapdump so you may find you have to downgrade to a (much) older version.

**Comment by atar-axis** [comment]
Thing is, that only this package does have the Problem when running `meteor build`. We will try upgrading node and meteor though

**Comment by atar-axis** [comment]
i found it, we actually installed a wrong meteor version (the newer one) and built it with that but were running on the older one. this was due to an dockerfile `ARG` in the wrong place, which defined the meteor version and - since it was outside the `FROM` directive rendered empty. see here: https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact
