### ISSUE TITLE
Output heap to stream instead of file?

### ISSUE THREAD

**Issue by fiznool** [bnoordhuis/node-heapdump#51]
For debugging memory issues on systems such as Heroku, that don't have a writable filesystem, it would be great to have the option to stream the heapdump, so it can be consumed and sent elsewhere (e.g. an S3 bucket).

Unless there is another way?

**Comment by bnoordhuis** [comment]
It's not possible to call into JS land when the snapshot is being collected.  node-heapdump would have to buffer until it's finished but that means it's going to consume a ton of memory.

**Comment by fiznool** [comment]
Ok, no problem.

**Comment by raine** [comment]
AFAIK Heroku does have a writable file system, it's just not guaranteed to be persistent across restarts.
