### ISSUE TITLE
Heapdump for a child process or specified pid

### ISSUE THREAD

**Issue by jshkurti** [bnoordhuis/node-heapdump#52]
Hello,

Is it possible to perform a heapdump for a given child process or by pid ?

Thanks.

**Comment by bnoordhuis** [comment]
Yes, provided the child process has the module loaded.  Just send it a SIGUSR2.

**Comment by jshkurti** [comment]
Ok thanks.
Is there any way I could do it without interfering with the child source code though ?
Let's say I use ```child = child_process.spawn()``` and I want to perform a heapdump for that child.

**Comment by bnoordhuis** [comment]
You could perhaps write a small script that loads the module before loading the main application and spawn that instead.  But other than that, I'd say no, not possible.

**Comment by jshkurti** [comment]
Okay thank you sir :)

**Comment by bnoordhuis** [comment]
No problem.
