### ISSUE TITLE
Windows 8.1 node-gyp rebuild failure

### ISSUE THREAD

**Issue by Tackyshot** [bnoordhuis/node-heapdump#53]
Hey there, I was trying to install poop for one of my projects on my windows machine. However It always fails with "Failed at the heapdump@0.3.5 install script 'node-gyp rebuild'. "

Is there any suggestions you would be able to offer me for a solution?

the guys on the 'poop' repo directed me here for a possible solution.

**Comment by Tackyshot** [comment]
bump

**Comment by bnoordhuis** [comment]
Sorry, I must have missed the GH notification.  What do you see in npm-debug.log?

**Comment by randomsock** [comment]
Same here but installing [guvnor](https://github.com/tableflip/guvnor) on RHEL 6.5, Node 0.12.2.

Relevant extract from `npm-debug.log`:

	110388 verbose about to build /usr/local/lib/node_modules/guvnor
	110389 verbose unlock done using /root/.npm/_locks/guvnor-6357ef0c558a7d72.lock for /usr/local/lib/node_modules/guvnor
	110390 verbose stack Error: heapdump@0.3.5 install: `node-gyp rebuild`
	110390 verbose stack Exit status 1
	110390 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
	110390 verbose stack     at EventEmitter.emit (events.js:110:17)
	110390 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
	110390 verbose stack     at ChildProcess.emit (events.js:110:17)
	110390 verbose stack     at maybeClose (child_process.js:1015:16)
	110390 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
	110391 verbose pkgid heapdump@0.3.5
	110392 verbose cwd /usr/local
	110393 error Linux 2.6.32-431.11.2.el6.x86_64
	110394 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "guvnor" "--unsafe-perm"
	110395 error node v0.12.2
	110396 error npm  v2.7.4
	110397 error code ELIFECYCLE
	110398 error heapdump@0.3.5 install: `node-gyp rebuild`
	110398 error Exit status 1
	110399 error Failed at the heapdump@0.3.5 install script 'node-gyp rebuild'.
	110399 error This is most likely a problem with the heapdump package,
	110399 error not with npm itself.
	110399 error Tell the author that this fails on your system:
	110399 error     node-gyp rebuild
	110399 error You can get their info via:
	110399 error     npm owner ls heapdump
	110399 error There is likely additional logging output above.
	110400 verbose exit [ 1, true ]

**Comment by bnoordhuis** [comment]
npm is being unhelpful here, it hides the actual error.  What happens when you run `node-gyp rebuild` manually?

**Comment by randomsock** [comment]
**AAAARRRGGGH!**  I'm an idiot :disappointed:  Sorry, I've been staring at so many logs today I missed the one-liner earlier on that said `g++ not found` (first builds on a new machine) - installed that and of course it runs through fine.

However, a possible good thing out of this: I too have had to try developing Node on Windows before (:weary:), and perhaps the most painful part is building anything native, or a dependency that is.  So I'm wondering @Tackyshot if your MSBuild environment is setup correctly?  It won't be by default, unless you're already an MSVC++ developer maybe.  Have you been able to successfully build anything else native, like a db driver?

**Comment by Tackyshot** [comment]
@randomsock I am not a MSVC++ Developer, though i did download and install visual studio with the hope of solving the issue (no luck). Anyways, here is the error i recieved: 

```

gyp: binding.gyp not found (cwd: D:\work\personal\chipper) while trying to load
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\Username\AppData\Roaming\npm
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Users\\Username\\AppData\\Roaming\\npm\\node_modules\
gyp ERR! cwd D:\work\personal\chipper
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok

```

**Comment by randomsock** [comment]
`binding.gyp` should be in the root dir of that module, so that error suggests you're not in the right working dir (`...\chipper`?) when running `node-gyp rebuild`.  I don't know your setup but it might be `...\chipper\node_modules\heapdump`.  Can you check that and post the results again?

**Comment by MadLittleMods** [comment]
:+1:

**Comment by rainabba** [comment]
While C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp had 3.0.3, C:\Users\myusername\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp had 2.0.2.

I emptied the older folder and copied over the contents of the newer. Seems that npm isn't dealing well with the fact that there's the system node_modules AND user account node_modules THEN the actual project.

**Comment by MadLittleMods** [comment]
@bnoordhuis Has this been fixed? I don't see any new commits?

**Comment by bnoordhuis** [comment]
@MadLittleMods It's not an issue with node-heapdump but with people's local build environment.
