### ISSUE TITLE
Heapdumps generated size does not match process memory usage

### ISSUE THREAD

**Issue by geekyme** [bnoordhuis/node-heapdump#54]
My node process memory usage shows: 

![screen shot 2015-04-30 at 3 29 07 pm](https://cloud.githubusercontent.com/assets/977460/7408282/c943fbec-ef4d-11e4-9f86-67aa8e47863b.png)

However when I generate heapdumps of it, it does not even match it closely:

![image](https://cloud.githubusercontent.com/assets/977460/7408284/ce7ee8b0-ef4d-11e4-80ba-bfb33df18024.png)

**Comment by bnoordhuis** [comment]
There is an issue right now where objects are (not always?) accounted properly.  If you inspect the heap snapshot and everything has self size == retained size, you're hitting that issue.  It's especially problematic with Buffer objects because those are essentially small JS objects that retain references to large off-heap memory chunks.

Having said that, you're never going to see an exact match between the heap snapshot and RSS because the snapshot does not (and cannot) track memory allocated by the V8 and io.js runtime.

**Comment by geekyme** [comment]
got it ! :)

**Comment by askhogan** [comment]
@bnoordhuis thank you for your answer.  This may be better put into a v8 post, however, what recommendation do you give in hunting down a leak in this case?  I am having a problem where my linux server is reporting 1.5GB usage and the heapsnapshot is around 135mb.  When I open the heapdump it looks benign.  Is there another way to determine where this memory is going?

**Comment by bnoordhuis** [comment]
@askhogan Sorry, missed the notification for your comment.  Are you still having that issue?

**Comment by ibigbug** [comment]
@bnoordhuis I have the same issue. 

When `top` shows `iojs` use about 60m memory, I take a snapshot using SIGUSR2.

I load the snapshot in Chrome and the total size is only 13m.

**Comment by bnoordhuis** [comment]
@ibigbug Do Buffer objects in the heap snapshot have self size === retained size?

**Comment by ibigbug** [comment]
@bnoordhuis Yes, as you say. Any solutions for this situation ?

**Comment by bnoordhuis** [comment]
I think I know what's causing that (see [this comment](https://github.com/bnoordhuis/node-heapdump/issues/50#issuecomment-92300318) and [this one](https://github.com/bnoordhuis/node-heapdump/issues/50#issuecomment-106581153)) but if I'm right, it means the issue is in io.js / node.js, not node-heapdump.  I haven't had time yet to look into that.

**Comment by ibigbug** [comment]
Thans for your patient explanation and cool tool :+1:

**Comment by ronjouch** [comment]
@bnoordhuis I'm in the same boat, and don't understand if the `Buffer` chat above is relevant to my case. Here, `process.memoryUsage().heapTotal` reported 1.2GB at the moment of calling `heapdump.writeSnapshot`, but the .heapsnapshot file I get weighs only 185MB. The [README / Caveats section](https://github.com/bnoordhuis/node-heapdump#caveats) says:

> *On UNIX systems, the rule of thumb for creating a heap snapshot is that it requires memory twice the size of the heap at the time of the snapshot. If you end up with empty or truncated snapshot files, check the output of dmesg; you may have had a run-in with the system's OOM killer or a resource limit enforcing policy, like ulimit -u (max user processes) or ulimit -v (max virtual memory size).*

And in my case,

- System memory was plentiful at the time of the heapdump (5GB available, greater than 1.2GB * 2). `ulimit -v` returns `unlimited`
- `ulimit -u` returns `31826`, and was far from that many processes (it's a worker environment typically running three node processes, one master and two workers)
- Nothing stands out in `dmesg`.
- The callback I passed to `heapdump.writeSnapshot` *was* called.
- The `.heapsnapshot` loads fine in Chrome DevTools, and reports "1133MB":
![screenshot_heapsnapshot_2019-07-19-09:47:33](https://user-images.githubusercontent.com/522085/61539846-63aa2280-aa0a-11e9-8bf6-93908f96b6f7.png)

→ Does it sound like I have the full snapshot, or can it still be truncated? Anything else I'm missing? Thanks for the package 🙏.

Using heapdump@0.3.14, running on Node.js 10.16.0 in Amazon Linux with kernel 4.14.123-86.109.amzn1.x86_64

**Comment by bnoordhuis** [comment]
@ronjouch If your callback was called then the snapshot was generated successfully.

The on-disk file size can be smaller than the heap it describes because the file gets rid of a lot of the redundancy and slop that exists in live heaps.

Small example: a live object reference (i.e., graph edge) is 8 bytes on x64, the size of a pointer, but usually only 3 to 5 bytes on-disk. Edges make up a large part of most snapshots so those bytes add up.

**Comment by ronjouch** [comment]
> @ronjouch If your callback was called then the snapshot was generated successfully.

@bnoordhuis contradicting you on that. The last few days, I bumped half of my app servers to twice the RAM, leaving ample space to heapdump. On 29 runs of `writeSnapshot` when heap was 1.2GB and where callback was called with `err` = `null`,

- The 9 runs on machines with 8GB RAM (~5GB available at the time of `writeSnapshot`) produced snapshots between 1140MB and 1333MB.
- The 20 runs on machines with 4GB RAM (~1GB available at the time of `writeSnapshot`) produced snapshots between 100MB and 225MB.

So, the readme caveat is still appropriate, and could maybe also advise to compare the size of the snapshot to `process.memoryUsage().heapTotal` as a poor man's way to ensure it wasn't truncated. Detecting truncation and returning a non-`null` callback error would be cool, you know better than I do if it's feasible. Can submit a quick doc PR, and/or open a new issue if you want.

At any rate, thanks again for your work on the module 🙂 ! With the non-truncated heapdumps I was able to find the memleak and my app is running smooth again \o/ !

**Comment by bnoordhuis** [comment]
I'm not sure what you're contradicting. If you're expecting that RSS == heap size, that's a wrong expectation. There are a bunch of things in Node that don't show up accurately in heap snapshots (TLS sockets, usually any memory managed by native modules, etc.)

Truncation is something you can detect visually. A `.heapsnapshot` is just a big JSON file that you can inspect in an editor. If you're using vim: `%` will check that the first '{' has a matching '}'.

There is one area where heapdump can improve: disk I/O errors like EIO and ENOSPC are currently ignored. (There was no way of reporting those when heapdump forked a new process to write the snapshot.) I've fixed that in 8505f53.

**Comment by ronjouch** [comment]
@bnoordhuis

> Truncation is something you can detect visually. A `.heapsnapshot` is just a big JSON file that you can inspect in an editor. If you're using vim: `%` will check that the first '{' has a matching '}'.

Oh, thanks. Was expecting them to be binary, had never looked at them directly. You're right, they're not truncated.

> I'm not sure what you're contradicting. If you're expecting that RSS == heap size, that's a wrong expectation. There are a bunch of things in Node that don't show up accurately in heap snapshots (TLS sockets, usually any memory managed by native modules, etc.)

That's not what I was expecting. I was expecting `process.memoryUsage().heapTotal` (which I measured right before calling `heapdump.writeSnapshot`) to have a size roughly similar to the size of the heapsnapshot file.

Instead, what I see reliably is that, with code writing a snapshot when heapTotal reaches 1.2GB (out of a Node 10 heap maxing at default 1.4GB),

- Inside machines with 4GB RAM, written snapshots are ~ 1GB.
- Inside machines with 8GB RAM, written snapshots are ~ 150MB.

This, and the readme caveat, is what made me suspect truncation. And even though I'm now convinced no truncation happened, I still don't understand what's going on 😄. What am I missing?!

> There is one area where heapdump can improve: disk I/O errors like EIO and ENOSPC are currently ignored. (There was no way of reporting those when heapdump forked a new process to write the snapshot.) I've fixed that in [8505f53](https://github.com/bnoordhuis/node-heapdump/commit/8505f537d1272c7506adad8af79690b598d5a1ec).

Cool! Thanks.
