### ISSUE TITLE
heapdump with node v0.12.4

### ISSUE THREAD

**Issue by bsimpson53** [bnoordhuis/node-heapdump#55]
```
# node -v
v0.12.4
# heapdump
0.3.5
```

When I require heapdump I get the following error:

```
Error: Cannot find module '../build/Debug/addon'
     at Function.Module._resolveFilename (module.js:336:15)
     at Function.Module._load (module.js:278:25)
     at Module.require (module.js:365:17)
     at require (module.js:384:17)
     at Object.<anonymous> (/home/app/node_modules/heapdump/lib/main.js:18:15)
     at Module._compile (module.js:460:26)
     at Object.Module._extensions..js (module.js:478:10)
     at Module.load (module.js:355:32)
     at Function.Module._load (module.js:310:12)
     at Module.require (module.js:365:17)
     at require (module.js:384:17)
```

There's no errors from ```node-gyp rebuild``` and ```build/Release/addon.node``` is there.

**Comment by bsimpson53** [comment]
FYI, I'm running ```ubuntu 14.04```, with docker, the base container I'm running is ```node:0.12``` (this is the official node image which is built on debian).

When I run without docker involved (and therefore without the debian based image) heapdump works fine for node v0.12.4 and node v0.10.28

Interestingly, but not relevant, my memory leak goes away with v0.10.x

**Comment by bnoordhuis** [comment]
What do `file build/Release/addon.node` and `file $(which node)` print?  It's possible there's some kind of mismatch.

**Comment by johncokos** [comment]
I'm having the same issue ..

sh-4.1# file build/Release/addon.node
build/Release/addon.node: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, not stripped

sh-4.1# file $(which node)
/usr/local/bin/node: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.9, not stripped

**Comment by bnoordhuis** [comment]
Different but not that different that they're incompatible.

Frankly, I've no idea what would be causing the load error.  It doesn't sound like it's specifically a heapdump issue but I can't say for sure.

What happens when you run `node -p 'require("./node_modules/heapdump/build/Release/addon")'`?

**Comment by johncokos** [comment]
sh-4.1# node -p 'require("./node_modules/heapdump/build/Release/addon")'
{ kForkFlag: 1,
  kSignalFlag: 2,
  configure: [Function],
  writeSnapshot: [Function] }

**Comment by bnoordhuis** [comment]
Thanks.  I don't think it's a heapdump issue then, if the module is loadable.  I speculate it has something to do with how the image(s) are mounted but I can only guess what.  If you figure it out and it's something that can be worked around, let me know.

**Comment by johncokos** [comment]
I ended up figuring it out ... we have a dual system.  Most developers work with the full source code of our app, and therefore, npm install works just fine, and there are no issues with heapdump getting loaded.

However, for our docker users, this issue was cropping up inside of the container causing the app within not to fire.  The root cause was that the container was being built with a full copy of the application (i.e.  node modules were being brought in with it) rather than the application going through the proper "npm install" process within the container before starting.

In the end, if you have done an npm install of heapdump on a mac, and then copy that node module into a centos docker container, it ain't gonna work :)

Once I changed the container to build it on its own, everything was fine.

Thanks for being so responsive.

**Comment by bnoordhuis** [comment]
Glad to hear it's working now. :-)

**Comment by bsimpson53** [comment]
Hi there,

Sorry I've been tied up, I had trashed the containers I was using where this happened and reverted to an earlier version of node. I was hoping to have time to rebuild and replicate.

I don't have a dual set-up as described, the npm build takes place within the container.

Sorry not to have updated, if I hit it again I will re-raise.

**Comment by bnoordhuis** [comment]
Thanks for following up, @bsimpson53.

**Comment by chollier** [comment]
I was getting the same issue, I don't have a dual-set up and the npm install is in the Dockerfile (it is that one https://github.com/joyent/docker-node/blob/975349606a637b266d7ecf7eae3b009f59716e74/0.12/onbuild/Dockerfile).
However if you look at what's happening, the current directory is copied after `npm install` is run, hence if you had `npm install`-ed locally before, these Mac files would get copied as well.

I added `node_modules` to my `.dockerignore` to solve that.

**Comment by francisdb** [comment]
requiring all the build tools (build-essential) in the container will blow up it's size :-s
could maybe try a build in one container and extracting everything out to a fresh container

**Comment by khushbookatta** [comment]
I am also facing the same issue and not able to install heap dump. Can anyone suggest the solution it. 
No dual set up is available.
