### ISSUE TITLE
In what part/s of an app where it is good to use heapdump

### ISSUE THREAD

**Issue by aireol** [bnoordhuis/node-heapdump#56]
In what parts of my app should I use `heapdump` to collect heap snapshot? Is it enough to have one in my main __node.js__ app or should I place it on some of my __models__ (speculated to cause memory leaks)?

Thanks for your help

**Comment by bnoordhuis** [comment]
Heap snapshots are global, they capture the whole JS heap, not just parts of it.  I'd say the best place to include the module is in your main script.
