### ISSUE TITLE
Build failure for io.js 3.0.0

### ISSUE THREAD

**Issue by d00rman** [bnoordhuis/node-heapdump#61]
heapdump v0.3.6 [fails to buid](https://travis-ci.org/wikimedia/restbase/jobs/74164374) for io.js 3.0.0. It was building [just fine](https://travis-ci.org/wikimedia/restbase/jobs/74022510) for io.js 2.5.0. Are there any plans to support io.js 3.0.0 ?

**Comment by d00rman** [comment]
Thank you for your quick reaction @bnoordhuis ! However, v0.3.7 builds against iojs 3.0.0 are still [failing](https://travis-ci.org/d00rman/restbase/jobs/74210955). All is fine for [iojs 2.5.0 builds](https://travis-ci.org/d00rman/restbase/jobs/74218805).

**Comment by bnoordhuis** [comment]
That's not related to node-heapdump but to V8.  It's a C++11 project now, that means you need at least gcc 4.8 or clang 3.4.
