### ISSUE TITLE
Is python or G++ needed for creating the heapdump?

### ISSUE THREAD

**Issue by paulrutter** [bnoordhuis/node-heapdump#63]
I'm creating a Docker image where the heapdump module is used. 
When building the image (running npm install), i need Python, make and G++ to build the heapdump module.

Do i still need these packages after building the module?
If not, i can remove these libraries after calling npm install and thus making my Docker image much smaller.

**Comment by bnoordhuis** [comment]
It's okay to remove them after building the module.

**Comment by paulrutter** [comment]
Ok, thanks :)
