### ISSUE TITLE
Allow to disable the signal handler without an environment variable

### ISSUE THREAD

**Issue by jguepin** [bnoordhuis/node-heapdump#64]
It would be great to be able to disable the signal handler by passing a configuration object when requiring node-heapdump. This is possible with the `NODE_HEAPDUMP_OPTIONS` variable, but environment variables are not always convenient.

Some modules use the SIGUSR2 signal, like [nodemon](https://github.com/remy/nodemon) does when restarting the server.

**Comment by Bacto** [comment]
Hi @jguepin,
Can't you just fix it with ```process.env```?

```process.env.NODE_HEAPDUMP_OPTIONS = <...>;```

**Comment by bnoordhuis** [comment]
Since it been two years and no one else asked for this feature, I'll go ahead and close this out.  Thanks for the suggestion, though.
