### ISSUE TITLE
Support Node.js 4.1.1

### ISSUE THREAD

**Issue by paulrutter** [bnoordhuis/node-heapdump#68]
On Windows, I cannot build the heapdump package successfully for Node.js 4.1.1.
It did work on Node.js 0.12.x.

Is Node.js 4.x going to be supported in the near future?

**Comment by bnoordhuis** [comment]
Can you be more specific about what errors you're getting?  v4.x is supported and has been since the day it was released.

**Comment by paulrutter** [comment]
Ok, thanks for your response.
I just thought about the fact that since i upgraded Node.js, i haven't updated node-gyp (and it's dependencies on Windows 8), see https://github.com/nodejs/node-gyp.

I will try to upgrade my tooling and then try again.
If it works, i will close the issue.
If not, i will post the error here.

**Comment by paulrutter** [comment]
Ah, after upgrading to VS Express C++ 2013 (http://www.microsoft.com/en-gb/download/details.aspx?id=44914) building the heapdump module works fine:

```
C:\gitnode_modules\heapdump>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  heapdump.cc
     Creating library C:\git\node_modules\heapdump\build\Release\addon.lib and object C:\git\node_modules\heapdump\build\Release\addon.exp
  Generating code
  Finished generating code
  addon.vcxproj -> C:\git\node_modules\heapdump\build\Release\\addon.node
```
