### ISSUE TITLE
compatible for nodejs 4.x

### ISSUE THREAD

**Issue by py8765** [bnoordhuis/node-heapdump#73]
when?

**Comment by py8765** [comment]
In file included from /home/py/.node-gyp/4.1.2/include/node/node.h:42:0,
                 from ../src/heapdump.cc:15:
/home/py/.node-gyp/4.1.2/include/node/v8.h:336:1: error: expected unqualified-id before ‘using’
/home/py/.node-gyp/4.1.2/include/node/v8.h:469:1: error: expected unqualified-id before ‘using’
/home/py/.node-gyp/4.1.2/include/node/v8.h:852:1: error: expected unqualified-id before ‘using’
../src/heapdump.cc:52:11: error: ‘v8::Handle’ has not been declared
make: *** [Release/obj.target/addon/src/heapdump.o] Error 1
make: Leaving directory `/home/py/Workspace/nodejs/test/chatofpomelo/game-server/node_modules/heapdump/build

**Comment by bnoordhuis** [comment]
You need a C++11-capable compiler, g++ >= 4.8.2 or clang++ >= 3.4.
