### ISSUE TITLE
Why is forking fundamentally incompatible with node.js v0.12+?

### ISSUE THREAD

**Issue by ebdrup** [bnoordhuis/node-heapdump#74]
What an awesome module!
You write that forking is fundamentally incompatible with node.js v0.12, could you explain a bit more why this is the case?

Suppose you would do your own analysis of the heapdump instead of using Chrome devtools, so you don't care about the comparison in chrome devtools not working. Would it be possible to use forking on node 4.2?

**Comment by bnoordhuis** [comment]
I didn't want to burden the README with (to most users) too much detail but it's explained in the commit log of 57c849c2.  In a nutshell, the version of V8 in v0.12 uses threads.  When you fork, only the calling thread is cloned to the new process.  V8 however still expects the other threads to be there and deadlocks as a result.

**Comment by ebdrup** [comment]
Thanks a lot for taking the time to answer my question. The reason I asked was because I was contemplating automatically detecting memoryleaks in a production environment. By taking a heapdump every say 10 minutes. Shipping it off to a service for analysis outside the production system. 




For that a non-blocking an preferably streaming heapdump would be perfect. It wouldn't matter that it would be a bit "incorrect". 




Non-blocking as not to hog the cpu. And streaming (http) as to not hog memory, so there would be minimal impact on the running system. 




But that seem like quite a bit of work. If even possible.

**Comment by bnoordhuis** [comment]
My company's [APM product](https://www.npmjs.com/package/strong-agent) has a mode for analyzing the heap at fixed intervals, grep the README for `agent.metrics.startTrackingObjects()`.  It's like memwatch but more accurate and with less overhead (and actively maintained - memwatch doesn't work with newer versions of node.js.)

We're working on an improved version for node.js v4.0+ that tells you by file name and line number where your source code is leaking resources.  That's still under development though, no ETA yet.

**Comment by ebdrup** [comment]
Ok thanks a lot, we'll try it out. We got a memoryleak in prod after upgrading from node 0.10 to 4.2. We updated a lot of dependencies at the same time to work on 4.2 so pinpointing the problem is not straight forward. 




You guys should buy some adwords for "node.js memoryleaks" we didn't come across your product in our googeling. 




Memwatch-next actually works on latest node. But the impact on the system is too big to run in prod. I think it's because it runs the leak analysis as well as dumping the heap. Also the analysis is very crude. 




I was thinking that you need to compare at least 3 heapdumps in the analysis so you can filter away temporary allocations for things in progress during the dump.

**Comment by bnoordhuis** [comment]
> You guys should buy some adwords for "node.js memoryleaks" we didn't come across your product in our googeling.

You know, I'm not even sure if we run any adwords campaigns.  Our customers are predominantly Fortune 500 companies and adwords don't really work on companies that size.  Any deal we close in under three months is lightning fast!

**Comment by ChrisCinelli** [comment]
Does `node-heapdump` work on Node 4.2.2 with sync writing?

**Comment by bnoordhuis** [comment]
Yes.
