### ISSUE TITLE
node-gyp rebuild error

### ISSUE THREAD

**Issue by ben5Git** [bnoordhuis/node-heapdump#75]
i am sorry my english is not very well :(

i can't install heapdump

log  as  this --->

localhost:node-heapdump kevin$ sudo node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.2.0
gyp info using node@4.2.2 | darwin | x64
gyp info spawn /usr/bin/python
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/yixin/tools/node-heapdump/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/yixin/.node-gyp/4.2.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/yixin/.node-gyp/4.2.2',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/yixin/tools/node-heapdump',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/addon/src/heapdump.o
  SOLINK_MODULE(target) Release/addon.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/addon.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/yixin/tools/node-heapdump
gyp ERR! node -v v4.2.2
gyp ERR! node-gyp -v v3.2.0
gyp ERR! not ok

**Comment by bnoordhuis** [comment]
> ld: library not found for -lgcc_s.10.5

That's not a node-heapdump issue.  Make sure your system is fully up to date, including xcode and xcode command line tools.  You may have to reboot afterwards.

If it still doesn't work, google around for that error message for more things to try.  Good luck.

**Comment by ben5Git** [comment]
Thanks ~
