### ISSUE TITLE
Stuck on "building postorder index" with node.js v4.2.3

### ISSUE THREAD

**Issue by wision** [bnoordhuis/node-heapdump#76]
Hello,

I've generated dump file with node-heapdump 0.3.7 and node 4.2.3 and I'm stuck on `building postorder index`. When I try to load the dump into chrome it does try to build the index for 10-20 seconds and then the DevTools bar just closes itself (before that, it eats about 2gb of ram). I have no problem doing this with node 0.10.x.

Any idea what could I do about it? Thanks.

**Comment by bnoordhuis** [comment]
You are probably experiencing https://github.com/bnoordhuis/node-heapdump/issues/50#issuecomment-106581153.  There is unfortunately not much that can be done at this time.

**Comment by ChALkeR** [comment]
Per https://github.com/bnoordhuis/node-heapdump/issues/50#issuecomment-184899165, try opening Settings in the Chrome Developer Tools (three dots menu at the top right of Chrome Developer Tools → Settings) and enable the «Show advanced heap snapshot properties» checkbox under «Profiler», then reload your heapdump (no need to take a new heapdump).

Does that solve the problem?
