### ISSUE TITLE
Taking a heapdump take a lot of ram that is not released

### ISSUE THREAD

**Issue by ChrisCinelli** [bnoordhuis/node-heapdump#81]
Running on Node 4.3.1. I am looking at the monitor graph on one of machine. When I create a heapdump (through an express route). After I call the route the first time I see a spike in the memory consumption. The memory is never released.

<img width="456" alt="screen shot 2016-03-03 at 12 15 35 pm" src="https://cloud.githubusercontent.com/assets/153101/13507943/dfb2170e-e139-11e5-874b-74e510b2b273.png">
The step between 3 Mar and 4:00 is when I took the first heapdump.

 Is heapdump ever releasing the memory used?
This is the code:

```
let heapdump = require('heapdump');

server.get('/captureHeap', (req, res, next) => {
  //See https://strongloop.com/strongblog/how-to-heap-snapshots/ and https://developer.chrome.com/devtools/docs/heap-profiling
    
 // Here we check if the user is allowed to take the snapshot.
 // ... 
 // 
  res.header('Content-Type', 'text/html');
  res.write("captureHeap... during this process the server will be irresponsive... <br>");
  let start = new Date();
  heapdump.writeSnapshot();
  fs.readdir(".", function(err, files){
    if(err){
      res.write('Error:'+err);
      res.end();
      return;
    }

    let diff = new Date() - start;
    res.write('Done in '+diff+' ms!');

    let hasBuild = false;
    for (var i = 0; i < files.length; i++) {
      if(files[i] == 'build'){
        hasBuild = true;
        break;
      }
    }

    //Move the file to the public folder and create a link.
    let html = "";
    for (var i = 0; i < files.length; i++) {
      let file = files[i];
      if (file.match(/heapdump.*heapsnapshot/) ){
        let dest = "."+(hasBuild ? "/build" : "")+"/public/"+file;
        fs.rename("./"+file, dest);
        html += "Download the file here: <a href='"+file+"'>"+file+"</a><br>";
      }
    }

    res.write(html);
    res.end();
  });
});
```

**Comment by bnoordhuis** [comment]
It should, it calls

**Comment by bnoordhuis** [comment]
It should, it calls `v8::HeapSnapshot::Delete()` after it's done writing out the heap snapshot.  I can't discern from your graph what you're measuring (RSS, VSS) but it's possible the memory is released but not returned to the operating system.

**Comment by bnoordhuis** [comment]
FWIW, I can't reproduce what you're seeing with a moderately complex application; RSS memory usage levels off after a few snapshots.  I'm using node v6.0.0-pre, however.

**Comment by ChrisCinelli** [comment]
I tried on node 4.3.1 and it behave the same.
However only the first call produce a step. If I call that endpoint again I see a spike but it goes down to how it was before the call.
The graph is produced by tutum.co and it is relative to the docker container but I am not completely sure if it is just RSS.

**Comment by bnoordhuis** [comment]
I'll close this because I can't reproduce.  If you're seeing a one-time spike, it's probably V8 allocating memory for the initial housekeeping.
