### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by nodejs1208** [bnoordhuis/node-heapdump#84]
npm install error (window 7 64x node 4.4.4)

C:\Users\a\Desktop\새 폴더>npm install

> heapdump@0.3.7 install C:\Users\a\Desktop\새 폴더
> node-gyp rebuild

C:\Users\a\Desktop\새 폴더>if not defined npm_config_node_gyp (node "C:\Pro
gram Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp
\bin\node-gyp.js" rebuild )  else (node "" rebuild )
이 솔루션의 프로젝트를 한 번에 하나씩 빌드합니다. 병렬 빌드를 사용하려면 "/m" 스
위치를 추가하십시오.
  heapdump.cc
..\src\heapdump.cc(15): fatal error C1083: 포함 파일을 열 수 없습니다. 'node.h':
 No such f
ile or directory [C:\Users\a\Desktop\새 폴더\build\addon.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\a\Desktop\새 폴더
gyp ERR! node -v v4.4.4
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! heapdump@0.3.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the heapdump@0.3.7 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the heapdump package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs heapdump
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls heapdump
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\a\Desktop\새 폴더\npm-debug.log

C:\Users\a\Desktop\새 폴더>

npm-debug.txt 

1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@2.15.1
3 info using node@v4.4.4
4 verbose readDependencies loading dependencies from C:\Users\a\Desktop\새 폴더\package.json
5 verbose install where, deps [ 'C:\\Users\\a\\Desktop\\새 폴더', [ 'shelljs', 'tap' ] ]
6 verbose install where, peers [ 'C:\\Users\\a\\Desktop\\새 폴더', [] ]
7 verbose installManyTop reading for lifecycle C:\Users\a\Desktop\새 폴더\package.json
8 info preinstall heapdump@0.3.7
9 verbose installManyTop reading scoped package data from C:\Users\a\Desktop\새 폴더\node_modules\shelljs\package.json
10 verbose installManyTop reading scoped package data from C:\Users\a\Desktop\새 폴더\node_modules\tap\package.json
11 info package.json shelljs@0.3.0 license should be a valid SPDX license expression
12 info package.json tap@0.4.13 license should be a valid SPDX license expression
13 verbose readDependencies loading dependencies from C:\Users\a\Desktop\새 폴더\package.json
14 verbose targetResolver reading package data from C:\Users\a\Desktop\새 폴더\node_modules\shelljs\package.json
15 verbose targetResolver reading package data from C:\Users\a\Desktop\새 폴더\node_modules\tap\package.json
16 verbose targetResolver reading package data from C:\Users\a\Desktop\새 폴더\node_modules\.bin\shjs\package.json
17 verbose targetResolver reading package data from C:\Users\a\Desktop\새 폴더\node_modules\.bin\shjs.cmd\package.json
18 verbose targetResolver reading package data from C:\Users\a\Desktop\새 폴더\node_modules\.bin\tap\package.json
19 verbose targetResolver reading package data from C:\Users\a\Desktop\새 폴더\node_modules\.bin\tap.cmd\package.json
20 verbose already installed skipping tap@~0.4.12 C:\Users\a\Desktop\새 폴더
21 verbose already installed skipping shelljs@~0.3.0 C:\Users\a\Desktop\새 폴더
22 silly install resolved []
23 info build C:\Users\a\Desktop\새 폴더
24 info linkStuff heapdump@0.3.7
25 silly linkStuff heapdump@0.3.7 has C:\Users\a\Desktop as its parent node_modules
26 verbose linkBins heapdump@0.3.7
27 verbose linkMans heapdump@0.3.7
28 verbose rebuildBundles heapdump@0.3.7
29 verbose rebuildBundles [ '.bin', 'shelljs', 'tap' ]
30 info install heapdump@0.3.7
31 verbose unsafe-perm in lifecycle true
32 info heapdump@0.3.7 Failed to exec install script
33 verbose stack Error: heapdump@0.3.7 install: `node-gyp rebuild`
33 verbose stack Exit status 1
33 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:217:16)
33 verbose stack     at emitTwo (events.js:87:13)
33 verbose stack     at EventEmitter.emit (events.js:172:7)
33 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
33 verbose stack     at emitTwo (events.js:87:13)
33 verbose stack     at ChildProcess.emit (events.js:172:7)
33 verbose stack     at maybeClose (internal/child_process.js:827:16)
33 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
34 verbose pkgid heapdump@0.3.7
35 verbose cwd C:\Users\a\Desktop\새 폴더
36 error Windows_NT 6.1.7601
37 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
38 error node v4.4.4
39 error npm  v2.15.1
40 error code ELIFECYCLE
41 error heapdump@0.3.7 install: `node-gyp rebuild`
41 error Exit status 1
42 error Failed at the heapdump@0.3.7 install script 'node-gyp rebuild'.
42 error This is most likely a problem with the heapdump package,
42 error not with npm itself.
42 error Tell the author that this fails on your system:
42 error     node-gyp rebuild
42 error You can get information on how to open an issue for this project with:
42 error     npm bugs heapdump
42 error Or if that isn't available, you can get their info via:
42 error
42 error     npm owner ls heapdump
42 error There is likely additional logging output above.
43 verbose exit [ 1, true ]

**Comment by bnoordhuis** [comment]
> ..\src\heapdump.cc(15): fatal error C1083: 포함 파일을 열 수 없습니다. 'node.h':

I can't read the error message but I assume it's complaining that node.h can't be found.  node-gyp dowloads the necessary SDK, make sure that's working.  Try deleting ~/.node-gyp and running `npm install` again.
