### ISSUE TITLE
windows7 x64 can not install this module

### ISSUE THREAD

**Issue by zouchengzhuo** [bnoordhuis/node-heapdump#86]
node-gyp rebuild fail

**Comment by bnoordhuis** [comment]
Closing, unhelpful bug report.

**Comment by zouchengzhuo** [comment]
"node-gyp configure build "
this command must cd to node_modules/heapdump directory,otherwise it will fail

**Comment by bnoordhuis** [comment]
If you `npm install heapdump`, npm runs node-gyp automatically for you.
