### ISSUE TITLE
Build error on windows 

### ISSUE THREAD

**Issue by deepalitandel** [bnoordhuis/node-heapdump#88]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli   'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'heapdump@0.3.7' ]
2 info using npm@2.14.7
3 info using node@v4.2.2
4 verbose install initial load of D:\performanceEngineering\hl7-example\package.json
5 warn package.json hl7-example@1.0.0 No description
6 warn package.json hl7-example@1.0.0 No repository field.
7 warn package.json hl7-example@1.0.0 No README data
8 verbose installManyTop reading scoped package data from D:\performanceEngineering\hl7-example\node_modules\fs\package.json
9 verbose installManyTop reading scoped package data from D:\performanceEngineering\hl7-example\node_modules\node-gyp\package.json
10 verbose installManyTop reading scoped package data from D:\performanceEngineering\hl7-example\node_modules\npm\package.json
11 verbose installManyTop reading scoped package data from D:\performanceEngineering\hl7-example\node_modules\simple-hl7\package.json
12 verbose installManyTop reading scoped package data from D:\performanceEngineering\hl7-example\node_modules\v8-profiler\package.json
13 info package.json fs@0.0.2 fs is also the name of a node core module.
14 info package.json fs@0.0.2 No description
15 info package.json fs@0.0.2 No repository field.
16 verbose readDependencies loading dependencies from D:\performanceEngineering\hl7-example\package.json
17 silly cache add args [ 'heapdump@0.3.7', null ]
18 verbose cache add spec heapdump@0.3.7
19 silly cache add parsed spec Result {
19 silly cache add   raw: 'heapdump@0.3.7',
19 silly cache add   scope: null,
19 silly cache add   name: 'heapdump',
19 silly cache add   rawSpec: '0.3.7',
19 silly cache add   spec: '0.3.7',
19 silly cache add   type: 'version' }
20 silly addNamed heapdump@0.3.7
21 verbose addNamed "0.3.7" is a plain semver version for heapdump
22 silly mapToRegistry name heapdump
23 silly mapToRegistry using default registry
24 silly mapToRegistry registry https://registry.npmjs.org/
25 silly mapToRegistry uri https://registry.npmjs.org/heapdump
26 verbose addNameVersion registry:https://registry.npmjs.org/heapdump not in flight; fetching
27 verbose request uri https://registry.npmjs.org/heapdump
28 verbose request no auth needed
29 info attempt registry request try #1 at 5:35:51 PM
30 verbose request id 90d68765e4b0be73
31 verbose etag "CYL95FN6UAKAA7Q4K5P7GCQ1O"
32 http request GET https://registry.npmjs.org/heapdump
33 http 304 https://registry.npmjs.org/heapdump
34 verbose headers { date: 'Wed, 03 Aug 2016 12:05:51 GMT',
34 verbose headers   via: '1.1 varnish',
34 verbose headers   'cache-control': 'max-age=300',
34 verbose headers   etag: '"CYL95FN6UAKAA7Q4K5P7GCQ1O"',
34 verbose headers   age: '268',
34 verbose headers   connection: 'keep-alive',
34 verbose headers   'x-served-by': 'cache-sin6923-SIN',
34 verbose headers   'x-cache': 'HIT',
34 verbose headers   'x-cache-hits': '3',
34 verbose headers   'x-timer': 'S1470225951.934718,VS0,VE0',
34 verbose headers   vary: 'Accept-Encoding' }
35 silly get cb [ 304,
35 silly get   { date: 'Wed, 03 Aug 2016 12:05:51 GMT',
35 silly get     via: '1.1 varnish',
35 silly get     'cache-control': 'max-age=300',
35 silly get     etag: '"CYL95FN6UAKAA7Q4K5P7GCQ1O"',
35 silly get     age: '268',
35 silly get     connection: 'keep-alive',
35 silly get     'x-served-by': 'cache-sin6923-SIN',
35 silly get     'x-cache': 'HIT',
35 silly get     'x-cache-hits': '3',
35 silly get     'x-timer': 'S1470225951.934718,VS0,VE0',
35 silly get     vary: 'Accept-Encoding' } ]
36 verbose etag https://registry.npmjs.org/heapdump from cache
37 verbose get saving heapdump to C:\Users\deepalit\AppData\Roaming\npm-cache\registry.npmjs.org\heapdump.cache.json
38 silly cache afterAdd heapdump@0.3.7
39 verbose afterAdd C:\Users\deepalit\AppData\Roaming\npm-cache\heapdump\0.3.7\package\package.json not in flight; writing
40 verbose afterAdd C:\Users\deepalit\AppData\Roaming\npm-cache\heapdump\0.3.7\package\package.json written
41 silly install resolved [ { name: 'heapdump',
41 silly install resolved     main: './lib/main',
41 silly install resolved     version: '0.3.7',
41 silly install resolved     description: 'Make a dump of the V8 heap for later inspection.',
41 silly install resolved     homepage: 'https://github.com/bnoordhuis/node-heapdump',
41 silly install resolved     author:
41 silly install resolved      { name: 'Ben Noordhuis',
41 silly install resolved        email: 'info@bnoordhuis.nl',
41 silly install resolved        url: 'http://bnoordhuis.nl/' },
41 silly install resolved     repository:
41 silly install resolved      { type: 'git',
41 silly install resolved        url: 'git://github.com/bnoordhuis/node-heapdump.git' },
41 silly install resolved     engines: { node: '>=0.10.0' },
41 silly install resolved     license: 'ISC',
41 silly install resolved     scripts: { test: 'tap test/test-*', install: 'node-gyp rebuild' },
41 silly install resolved     devDependencies: { shelljs: '~0.3.0', tap: '~0.4.12' },
41 silly install resolved     gypfile: true,
41 silly install resolved     gitHead: '3e308b302fb2d7beba5b1c4a6eaf92caba51cbf2',
41 silly install resolved     bugs: { url: 'https://github.com/bnoordhuis/node-heapdump/issues' },
41 silly install resolved     _id: 'heapdump@0.3.7',
41 silly install resolved     _shasum: 'f50df2b140e5cde7656638f4c384d683b0143298',
41 silly install resolved     _from: 'heapdump@0.3.7',
41 silly install resolved     _npmVersion: '2.13.3',
41 silly install resolved     _nodeVersion: '3.0.1-pre',
41 silly install resolved     _npmUser: { name: 'bnoordhuis', email: 'info@bnoordhuis.nl' },
41 silly install resolved     maintainers: [ [Object] ],
41 silly install resolved     dist:
41 silly install resolved      { shasum: 'f50df2b140e5cde7656638f4c384d683b0143298',
41 silly install resolved        tarball: 'https://registry.npmjs.org/heapdump/-/heapdump-0.3.7.tgz' },
41 silly install resolved     directories: {},
41 silly install resolved     _resolved: 'https://registry.npmjs.org/heapdump/-/heapdump-0.3.7.tgz',
41 silly install resolved     readme: 'ERROR: No README data found!' } ]
42 info install heapdump@0.3.7 into D:\performanceEngineering\hl7-example
43 info installOne heapdump@0.3.7
44 verbose installOne of heapdump to D:\performanceEngineering\hl7-example not in flight; installing
45 verbose lock using C:\Users\deepalit\AppData\Roaming\npm-cache_locks\heapdump-956b8e43ac81dcad.lock for D:\performanceEngineering\hl7-example\node_modules\heapdump
46 silly install write writing heapdump 0.3.7 to D:\performanceEngineering\hl7-example\node_modules\heapdump
47 verbose unbuild node_modules\heapdump
48 silly gentlyRm D:\performanceEngineering\hl7-example\node_modules\heapdump is being purged from base D:\performanceEngineering\hl7-example
49 verbose gentlyRm don't care about contents; nuking D:\performanceEngineering\hl7-example\node_modules\heapdump
50 verbose tar unpack C:\Users\deepalit\AppData\Roaming\npm-cache\heapdump\0.3.7\package.tgz
51 verbose tar unpacking to D:\performanceEngineering\hl7-example\node_modules\heapdump
52 silly gentlyRm D:\performanceEngineering\hl7-example\node_modules\heapdump is being purged
53 verbose gentlyRm don't care about contents; nuking D:\performanceEngineering\hl7-example\node_modules\heapdump
54 silly gunzTarPerm modes [ '777', '666' ]
55 silly gunzTarPerm extractEntry package.json
56 silly gunzTarPerm modified mode [ 'package.json', 436, 438 ]
57 silly gunzTarPerm extractEntry .npmignore
58 silly gunzTarPerm modified mode [ '.npmignore', 436, 438 ]
59 silly gunzTarPerm extractEntry README.md
60 silly gunzTarPerm modified mode [ 'README.md', 436, 438 ]
61 silly gunzTarPerm extractEntry LICENSE
62 silly gunzTarPerm modified mode [ 'LICENSE', 436, 438 ]
63 silly gunzTarPerm extractEntry .clang-format
64 silly gunzTarPerm modified mode [ '.clang-format', 436, 438 ]
65 silly gunzTarPerm extractEntry binding.gyp
66 silly gunzTarPerm modified mode [ 'binding.gyp', 436, 438 ]
67 silly gunzTarPerm extractEntry lib/main.js
68 silly gunzTarPerm modified mode [ 'lib/main.js', 436, 438 ]
69 silly gunzTarPerm extractEntry src/compat-inl.h
70 silly gunzTarPerm modified mode [ 'src/compat-inl.h', 436, 438 ]
71 silly gunzTarPerm extractEntry src/compat.h
72 silly gunzTarPerm modified mode [ 'src/compat.h', 436, 438 ]
73 silly gunzTarPerm extractEntry src/heapdump-posix.h
74 silly gunzTarPerm modified mode [ 'src/heapdump-posix.h', 436, 438 ]
75 silly gunzTarPerm extractEntry src/heapdump-win32.h
76 silly gunzTarPerm modified mode [ 'src/heapdump-win32.h', 436, 438 ]
77 silly gunzTarPerm extractEntry src/heapdump.cc
78 silly gunzTarPerm modified mode [ 'src/heapdump.cc', 436, 438 ]
79 silly gunzTarPerm extractEntry test/test-callback-without-filename.js
80 silly gunzTarPerm modified mode [ 'test/test-callback-without-filename.js', 436, 438 ]
81 silly gunzTarPerm extractEntry test/test-callback.js
82 silly gunzTarPerm modified mode [ 'test/test-callback.js', 436, 438 ]
83 silly gunzTarPerm extractEntry test/test-sigusr2.js
84 silly gunzTarPerm modified mode [ 'test/test-sigusr2.js', 436, 438 ]
85 verbose write writing to D:\performanceEngineering\hl7-example\node_modules\heapdump\package.json
86 info preinstall heapdump@0.3.7
87 verbose readDependencies loading dependencies from D:\performanceEngineering\hl7-example\node_modules\heapdump\package.json
88 verbose readDependencies loading dependencies from D:\performanceEngineering\hl7-example\node_modules\heapdump\package.json
89 silly install resolved []
90 verbose about to build D:\performanceEngineering\hl7-example\node_modules\heapdump
91 info build D:\performanceEngineering\hl7-example\node_modules\heapdump
92 info linkStuff heapdump@0.3.7
93 silly linkStuff heapdump@0.3.7 has D:\performanceEngineering\hl7-example\node_modules as its parent node_modules
94 verbose linkBins heapdump@0.3.7
95 verbose linkMans heapdump@0.3.7
96 verbose rebuildBundles heapdump@0.3.7
97 info install heapdump@0.3.7
98 verbose unsafe-perm in lifecycle true
99 info heapdump@0.3.7 Failed to exec install script
100 verbose unlock done using C:\Users\deepalit\AppData\Roaming\npm-cache_locks\heapdump-956b8e43ac81dcad.lock for D:\performanceEngineering\hl7-example\node_modules\heapdump
101 verbose stack Error: heapdump@0.3.7 install: `node-gyp rebuild`
101 verbose stack Exit status 1
101 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
101 verbose stack     at emitTwo (events.js:87:13)
101 verbose stack     at EventEmitter.emit (events.js:172:7)
101 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
101 verbose stack     at emitTwo (events.js:87:13)
101 verbose stack     at ChildProcess.emit (events.js:172:7)
101 verbose stack     at maybeClose (internal/child_process.js:818:16)
101 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
102 verbose pkgid heapdump@0.3.7
103 verbose cwd D:\performanceEngineering\hl7-example
104 error Windows_NT 6.1.7601
105 error argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "heapdump@0.3.7"
106 error node v4.2.2
107 error npm  v2.14.7
108 error code ELIFECYCLE
109 error heapdump@0.3.7 install: `node-gyp rebuild`
109 error Exit status 1
110 error Failed at the heapdump@0.3.7 install script 'node-gyp rebuild'.
110 error This is most likely a problem with the heapdump package,
110 error not with npm itself.
110 error Tell the author that this fails on your system:
110 error     node-gyp rebuild
110 error You can get their info via:
110 error     npm owner ls heapdump
110 error There is likely additional logging output above.
111 verbose exit [ 1, true ]
112 verbose unbuild node_modules\heapdump
113 info preuninstall heapdump@0.3.7
114 info uninstall heapdump@0.3.7
115 verbose unbuild rmStuff heapdump@0.3.7 from D:\performanceEngineering\hl7-example\node_modules
116 info postuninstall heapdump@0.3.7
117 silly gentlyRm D:\performanceEngineering\hl7-example\node_modules\heapdump is being purged from base D:\performanceEngineering\hl7-example
118 verbose gentlyRm don't care about contents; nuking D:\performanceEngineering\hl7-example\node_modules\heapdump
119 silly vacuum-fs purging D:\performanceEngineering\hl7-example\node_modules\heapdump
120 silly vacuum-fs quitting because other entries in D:\performanceEngineering\hl7-example\node_modules

**Comment by bnoordhuis** [comment]
What is the actual build error though?  npm is supremely unhelpful in that it doesn't log the output of node-gyp to the debug log.

**Comment by jmorales4** [comment]
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Github\FnetIdentityApi\node_modules\heapdump
gyp ERR! node -v v4.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "heapdump"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE

npm ERR! heapdump@0.3.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the heapdump@0.3.7 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the heapdump package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs heapdump
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls heapdump
npm ERR! There is likely additional logging output above.

**Comment by bnoordhuis** [comment]
@jmorales4 Can you post the full output?  Everything from you typing `npm install heapdump` onward.

**Comment by exilonX** [comment]
I get the same error. 
Full output:

> npm WARN package.json upuinterface@0.1.0 No repository field.
> npm WARN package.json upuinterface@0.1.0 No license field.
> 
> > heapdump@0.3.7 install C:\ARMONIA\AplicatiiWeb\sts-upu\FisaUPU\node_modules\heapdump
> > node-gyp rebuild
> 
> 
> C:\ARMONIA\AplicatiiWeb\sts-upu\FisaUPU\node_modules\heapdump>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
> Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
> C:\ARMONIA\AplicatiiWeb\sts-upu\FisaUPU\node_modules\heapdump\build\addon.vcxproj(20,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
> gyp ERR! build error
> gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
> gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
> gyp ERR! System Windows_NT 6.1.7601
> gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
> gyp ERR! cwd C:\ARMONIA\AplicatiiWeb\sts-upu\FisaUPU\node_modules\heapdump
> gyp ERR! node -v v0.12.7
> gyp ERR! node-gyp -v v2.0.1
> gyp ERR! not ok
> npm ERR! Windows_NT 6.1.7601
> npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "heapdump"
> npm ERR! node v0.12.7
> npm ERR! npm  v2.11.3
> npm ERR! code ELIFECYCLE
> 
> npm ERR! heapdump@0.3.7 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the heapdump@0.3.7 install script 'node-gyp rebuild'.
> npm ERR! This is most likely a problem with the heapdump package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp rebuild
> npm ERR! You can get their info via:
> npm ERR!     npm owner ls heapdump
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     C:\ARMONIA\AplicatiiWeb\sts-upu\FisaUPU\npm-debug.log
>

**Comment by bnoordhuis** [comment]
@exilonX Google around for that MSB4019 error.  It probably means node-gyp can't find the right Visual Studio install so try passing `--msvs_version=...` to npm.
