### ISSUE TITLE
Error: heapdump@0.3.7 install: `node-gyp rebuild`

### ISSUE THREAD

**Issue by esquare666** [bnoordhuis/node-heapdump#89]
Hi,

I am installing heapdump@0.3.7 on RHEL 7.2, and installation failed due to the below error

108201 verbose rebuild bundle /appl/apic/member/node_modules/apiconnect-collective-member/node_modules/heapdump
108202 info build /appl/apic/member/node_modules/apiconnect-collective-member/node_modules/heapdump
108203 info preinstall heapdump@0.3.7
108204 info linkStuff heapdump@0.3.7
108205 silly linkStuff heapdump@0.3.7 has /appl/apic/member/node_modules/apiconnect-collective-member/node_modules as its parent node_modules
108206 verbose linkBins heapdump@0.3.7
108207 verbose linkMans heapdump@0.3.7
108208 verbose rebuildBundles heapdump@0.3.7
108209 info install heapdump@0.3.7
108210 verbose unsafe-perm in lifecycle true
108211 info heapdump@0.3.7 Failed to exec install script
108212 verbose unlock done using /appl/apic/.npm/_locks/apiconnect-collective-me-80d5f3c2fe44d090.lock for /appl/apic/member/node_modules/apiconnect-collective-member
108213 verbose stack Error: heapdump@0.3.7 install: `node-gyp rebuild`
108213 verbose stack Exit status 1
108213 verbose stack     at EventEmitter.<anonymous> (/appl/apic/node/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
108213 verbose stack     at emitTwo (events.js:87:13)
108213 verbose stack     at EventEmitter.emit (events.js:172:7)
108213 verbose stack     at ChildProcess.<anonymous> (/appl/apic/node/lib/node_modules/npm/lib/utils/spawn.js:24:14)
108213 verbose stack     at emitTwo (events.js:87:13)
108213 verbose stack     at ChildProcess.emit (events.js:172:7)
108213 verbose stack     at maybeClose (internal/child_process.js:827:16)
108213 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
108214 verbose pkgid heapdump@0.3.7
108215 verbose cwd /appl/apic/member
108216 error Linux 3.10.0-327.10.1.el7.x86_64
108217 error argv "/appl/apic/node/bin/node" "/appl/apic/node/bin/npm" "install" "/appl/apic/software/apiconnect-collective-member-1.1.5.tgz"
108218 error node v4.4.4
108219 error npm  v2.15.1
108220 error code ELIFECYCLE
108221 error heapdump@0.3.7 install: `node-gyp rebuild`
108221 error Exit status 1
108222 error Failed at the heapdump@0.3.7 install script 'node-gyp rebuild'.
108222 error This is most likely a problem with the heapdump package,

python --version
Python 2.7.5

gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-4)

make -version
GNU Make 3.82
Built for x86_64-redhat-linux-gnu

**Comment by bnoordhuis** [comment]
Can you include the actual build error?  npm doesn't log it but it should be printed to the console.

**Comment by esquare666** [comment]
> heapdump@0.3.7 install /appl/apic/node/lib/node_modules/apiconnect-collective-member/node_modules/heapdump
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: connect ETIMEDOUT 104.20.23.46:443
gyp ERR! stack     at Object.exports._errnoException (util.js:870:11)
gyp ERR! stack     at exports._exceptionWithHostPort (util.js:893:20)
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1061:14)
gyp ERR! System Linux 3.10.0-327.10.1.el7.x86_64
gyp ERR! command "/appl/apic/node/bin/node" "/appl/apic/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /appl/apic/node/lib/node_modules/apiconnect-collective-member/node_modules/heapdump
gyp ERR! node -v v4.4.4
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm ERR! Linux 3.10.0-327.10.1.el7.x86_64
npm ERR! argv "/appl/apic/node/bin/node" "/appl/apic/node/bin/npm" "install" "-g" "/appl/apic/software/apiconnect-collective-member-1.1.5.tgz"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! heapdump@0.3.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the heapdump@0.3.7 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the heapdump package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs heapdump
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls heapdump
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /appl/apic/member/npm-debug.log

**Comment by bnoordhuis** [comment]
The salient bit:

> gyp ERR! stack Error: connect ETIMEDOUT 104.20.23.46:443

That is not a node-heapdump issue.  node-gyp tries to download the node.js SDK from https://nodejs.org/ in order to build the add-on but that times out on your system for some reason.

Sorry, not something I can help you with.  You can download the v4.4.4 source tarball from nodejs.org manually and point node-gyp to it with the `--tarball` switch or through the `npm_config_tarball` environment variable (convenient if you invoke node-gyp indirectly through npm.)

Good luck.
