### ISSUE TITLE
Comparison view is broken in node < 0.12 due to `HeapObjectsMap` being cleared

### ISSUE THREAD

**Issue by rf** [bnoordhuis/node-heapdump#96]
In heapdump.cc#128 there is a call to `HeapSnapshot::Delete()`. If it's the last snapshot, `HeapProfiler::DeleteAllSnapshots()` will get called (v8/src/api.cc#6277). In v8 versions < 3.23.18, this will delete the entire `HeapSnapshotsCollection` and reinstantiate it, which clears the `HeapObjectsMap`. So the object UIDs all get regenerated and the snapshots cannot be compared. This was fixed [here](https://chromium.googlesource.com/v8/v8/+/3.23.18%5E%21/#F9).

Removing that call to `HeapSnapshot::Delete()` would fix the issue but would also of course cause huge memory usage. I'm not super great at C++, but if there's a way to reach into the internal-namespaced objects and just delete the individual snapshot, that would work.

To be clear, this only affects Node 0.10.x. As of Node 0.12 the version of v8 is new enough to have the fix.

**Comment by bnoordhuis** [comment]
Thanks for the detailed bug report.  It's too bad v0.10 is EOL or we could have floated a fix in core.

To be honest, I'm not sure what to do about it now.  I could add v0.10-specific logic to retain the last snapshot but that's not very nice at the best of times and downright terrible when it sets off the OOM killer.

> if there's a way to reach into the internal-namespaced objects and just delete the individual snapshot

That won't work, I'm afraid.  Node doesn't export V8's internal functions and replicating the logic through judicious pointer casting will crash miserably with vendor builds that use a different V8.

**Comment by bnoordhuis** [comment]
I'll close this out because I don't think there is anything that can be done, or at least nothing that doesn't have unwanted side effects.
