### ISSUE TITLE
"npm i heapdump@0.3.8" does not rebuild the addon

### ISSUE THREAD

**Issue by RomanSaveljev** [bnoordhuis/node-heapdump#98]
We have noticed that installing freshly released 0.3.8 on raspberry pi does not trigger rebuilding the addon, so there is no `build/Release` folder.

**Comment by bnoordhuis** [comment]
I've noticed the same thing but I suspect it's a npm issue.  I received a similar report for another project (bnoordhuis/node-iconv#167) where manually running `node-gyp rebuild` fixed the issue.

**Comment by RomanSaveljev** [comment]
For the time being we have downgraded to 0.3.7

**Comment by andrewaustin** [comment]
We've ran into the same issue, if you need any information to debug we can provide whatever is needed.

**Comment by bnoordhuis** [comment]
It was an npm issue, see https://github.com/npm/npm/issues/16243.  I've published 0.3.9 as a workaround.
